// Generated by react_on_rails:generate_response_types. Do not edit by hand.

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

export interface ContactMessagesCreateResponse {
  message: string;
}

export interface ContactMessagesValidationErrorResponse {
  errors: {
    base?: string[];
    email?: string[];
    message?: string[];
    name?: string[];
  };
}

export interface RailsResponseTypes {
  'contact_messages.create': ContactMessagesCreateResponse;
  'contact_messages.validation_error': ContactMessagesValidationErrorResponse;
}

export type RailsResponseTypeName = keyof RailsResponseTypes;
export type RailsResponseType<TName extends RailsResponseTypeName> = RailsResponseTypes[TName];
