# This is the configuration used to check the rubocop source code.
# Check out: https://github.com/bbatsov/rubocop

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.1

  Include:
    - '**/Rakefile'
    - '**/config.ru'

  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'node_modules/**/.*'
    - 'node_modules/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'client/node_modules/**/*.*'
    - 'client/node_modules/**/.*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'spec/react_on_rails/dummy-for-generators/**/*'
    - 'spec/dummy/Procfile.*'
    - 'spec/dummy/bin/**/*'
    - 'spec/dummy/client/node_modules/**/*'
    - 'spec/dummy/client/node_modules/**/.*'
    - 'spec/dummy_no_webpacker/Procfile.*'
    - 'spec/dummy_no_webpacker/bin/**/*'
    - 'spec/dummy_no_webpacker/client/node_modules/**/*'
    - 'spec/dummy_no_webpacker/client/node_modules/**/.*'
    - 'gen-examples/examples/**/.*'
    - 'gen-examples/examples/**/*'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'spec/dummy/Gemfile'
    - 'spec/dummy_no_webpacker/Gemfile'

# Turn off until we require 2.3 ruby
Style/SafeNavigation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Lint/AssignmentInCondition:
  Exclude:
    - 'spec/dummy/bin/spring'

Lint/HandleExceptions:
  Exclude:
    - 'spec/dummy/bin/rails'
    - 'spec/dummy/bin/rake'

Metrics/AbcSize:
  Max: 28

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 150

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/MethodLength:
  Max: 41

Metrics/ModuleLength:
  Max: 180

Style/GlobalVars:
  Exclude:
    - 'spec/dummy/config/environments/development.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed
