# This is the configuration used to check the rubocop source code.
# Check out: https://github.com/bbatsov/rubocop
require:
  - "rubocop-performance"

# Todo: turn on rubocop-rspec
#  - "rubocop-rspec"

AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.5

  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'Gemfile'
    - '**/*.rb'
    - '**/*.rake'

  Exclude:
  <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
    - <%= path.sub(/^!! /, '') %>
  <% end %>
    - '**/node_modules/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'spec/fixtures/**/*'
    - 'spec/dummy/db/schema.rb'
    - 'spec/dummy/bin/**/*'
    - 'spec/loadable/bin/**/*'
    - 'spec/loadable/db/schema.rb'
    - 'node_modules/**/*'
    - 'coverage/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Naming/FileName:
  Exclude:
    - '**/Gemfile'

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/AbcSize:
  Max: 28

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 140

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/MethodLength:
  Max: 41

Metrics/ModuleLength:
  Max: 180

Style/GlobalVars:
  Exclude:
    - 'spec/dummy/config/environments/development.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
