# This is the configuration used to check the rubocop source code.
# Check out: https://github.com/bbatsov/rubocop

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'node_modules/**/*.*'
    - 'node_modules/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'client/node_modules/**/*.*'
    - 'client/node_modules/**/*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'spec/react_on_rails/dummy-for-generators/**/*'
    - 'spec/dummy/bin/**/*'
    - 'tmp/examples/**/*'

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Lint/AssignmentInCondition:
  Exclude:
    - 'spec/dummy/bin/spring'

# Offense count: 2
Lint/HandleExceptions:
  Exclude:
    - 'spec/dummy/bin/rails'
    - 'spec/dummy/bin/rake'

# Offense count: 1
Metrics/AbcSize:
  Max: 24

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 114

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

# Offense count: 9
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 41

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 150

# Offense count: 3
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Exclude:
    - 'spec/dummy/config/environments/development.rb'
