module ReactOnRails
  module Controller
    def redux_store: (
      String store_name,
      ?props: untyped,
      ?immediate_hydration: bool?
    ) -> void

    def redux_store_hydration_data: () -> String
  end
end
