common: &common
  adapter: postgresql
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || "localhost" %>
  port: <%= ENV['DB_PORT'] || "5432" %>

development:
  <<: *common
  database: loadable_development

test:
  <<: *common
  database: loadable_test

production:
  <<: *common
  database: loadable_production
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] %>
