# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cd24e99fc1b68f6cd1592e4db8c88c2b508dbd12a37dd0cef184eb46aa5e3512f386d02c7a29971b8e34a9daa627642fc4a03b9c49e28f1943ea9028c91ba47

test:
  secret_key_base: dc32615767de0980cff6d63e9c86e83e7975bdffaa8b8162032bd7b8626243561915b774b442843c7cce8059f10cca456071098939a7fc93e57fd134a78b164e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"].presence ||
   "8cd24e99fc1b68f6cd1592e4db8c88c2b508dbd12a37dd0cef184eb46aa5e3512f386d02c7a29971b8e34a9daa627642fc4a03b9c49e28f1943ea9028c91ba47" %>
