---
default:
  source_path: client/app
  source_entry_path: packs
  public_root_path: public
  cache_path: tmp/cache/shakapacker
  webpack_compile_output: false
  ensure_consistent_versioning: true
  additional_paths: &1 []
  cache_manifest: false
  nested_entries: true
  swc: true
development:
  source_path: client/app
  source_entry_path: packs
  public_root_path: public
  cache_path: tmp/cache/shakapacker
  webpack_compile_output: false
  ensure_consistent_versioning: true
  additional_paths: *1
  cache_manifest: false
  nested_entries: true
  compile: false
  public_output_path: webpack/development
  dev_server:
    https: false
    host: localhost
    port: 3035
    hmr: true
    client:
      overlay: true
    compress: true
    allowed_hosts: all
    pretty: true
    headers:
      Access-Control-Allow-Origin: "*"
    static:
      watch:
        ignored: "**/node_modules/**"
  swc: true
test:
  source_path: client/app
  source_entry_path: packs
  public_root_path: public
  cache_path: tmp/cache/shakapacker
  webpack_compile_output: false
  ensure_consistent_versioning: true
  additional_paths: *1
  cache_manifest: false
  nested_entries: true
  compile: false
  public_output_path: webpack/test
  swc: true
production:
  source_path: client/app
  source_entry_path: packs
  public_root_path: public
  cache_path: tmp/cache/shakapacker
  webpack_compile_output: false
  ensure_consistent_versioning: true
  additional_paths: *1
  cache_manifest: true
  nested_entries: true
  public_output_path: webpack/production
  compile: false
  swc: true
