# This is the configuration used to check the rubocop source code.
# Check out: https://github.com/bbatsov/rubocop
require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 3.0

  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'Gemfile'
    - '**/*.rb'
    - '**/*.rake'

  Exclude:
  <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
    - <%= path.sub(/^!! /, '') %>
  <% end %>
    - '**/node_modules/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'spec/fixtures/**/*'
    - 'spec/dummy/db/schema.rb'
    - 'spec/dummy/bin/**/*'
    - 'node_modules/**/*'
    - 'coverage/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Naming/FileName:
  Exclude:
    - '**/Gemfile'
    - '**/Rakefile'

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/AbcSize:
  Max: 28

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 140

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/MethodLength:
  Max: 41

Metrics/ModuleLength:
  Max: 180

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/react_on_rails/generators/dev_tests_generator_spec.rb'
    - 'spec/react_on_rails/generators/install_generator_spec.rb'

RSpec/MessageChain:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleDescribes:
  Exclude:
    - 'spec/dummy/spec/system/integration_spec.rb'

RSpec/MultipleMemoizedHelpers:
  Max: 12

RSpec:
  Language:
    Expectations:
      - change_text_expect_dom_selector
      - check_match

Style/GlobalVars:
  Exclude:
    - 'spec/dummy/config/environments/development.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
