# Inherits from root config
inherit_from: ../.rubocop.yml

AllCops:
  Exclude:
  <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
    - <%= path.sub(/^!! /, '') %>
  <% end %>
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'spec/dummy/db/schema.rb'
    - 'spec/dummy/bin/**/*'
    - 'bin/**/*'

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/react_on_rails/generators/dev_tests_generator_spec.rb'
    - 'spec/react_on_rails/generators/install_generator_spec.rb'

RSpec/MultipleDescribes:
  Exclude:
    - 'spec/dummy/spec/system/integration_spec.rb'

RSpec:
  Language:
    Expectations:
      - change_text_expect_dom_selector
      - check_match

Style/GlobalVars:
  Exclude:
    - 'spec/dummy/config/environments/development.rb'
