# frozen_string_literal: true

# require "English"
# require "open3"
# require "rainbow"
# require "active_support"
# require "active_support/core_ext/string"

# rubocop:disable Metrics/ModuleLength

module ReactOnRailsPro
  module Utils
    ###########################################################
    # PUBLIC API
    ###########################################################

    def self.rorp_puts(message)
      puts "[ReactOnRailsPro] #{message}"
    end

    # RSC Configuration Utility Methods
    # These methods were moved from ReactOnRails::Utils as they are Pro-only features

    def self.rsc_bundle_js_file_path
      return @rsc_bundle_path if @rsc_bundle_path && !Rails.env.development?

      bundle_name = ReactOnRailsPro.configuration.rsc_bundle_js_file
      @rsc_bundle_path = ReactOnRails::Utils.bundle_js_file_path(bundle_name)
    end

    def self.react_client_manifest_file_path
      return @react_client_manifest_path if @react_client_manifest_path && !Rails.env.development?

      file_name = ReactOnRailsPro.configuration.react_client_manifest_file
      @react_client_manifest_path = ReactOnRails::PackerUtils.asset_uri_from_packer(file_name)
    end

    # React Server Manifest is generated by the server bundle.
    # So, it will never be served from the dev server.
    def self.react_server_client_manifest_file_path
      return @react_server_manifest_path if @react_server_manifest_path && !Rails.env.development?

      asset_name = ReactOnRailsPro.configuration.react_server_client_manifest_file
      if asset_name.nil?
        raise ReactOnRailsPro::Error,
              "react_server_client_manifest_file is nil, ensure it is set in your configuration"
      end

      @react_server_manifest_path = ReactOnRails::Utils.bundle_js_file_path(asset_name)
    end

    def self.rsc_support_enabled?
      ReactOnRailsPro.configuration.enable_rsc_support
    end

    # Returns the current license status
    # @return [Symbol] One of :valid, :expired, :invalid, :missing
    def self.license_status
      LicenseValidator.license_status
    end

    def self.copy_assets
      return if ReactOnRailsPro.configuration.assets_to_copy.blank?

      ReactOnRailsPro::Request.upload_assets
    end

    # takes an array of globs, removes excluded_dependency_globs & returns a digest
    def self.digest_of_globs(globs)
      # NOTE: Dir.glob is not stable between machines, even with same OS. So we must sort.
      # .uniq was added to remove redundancies in the case digest_of_globs is used on a union of
      # dependency_globs & source code in order to create a cache key for production bundles
      # We've tested it to make sure that it adds less than a second even in the case of thousands of files
      files = Dir.glob(globs).uniq
      excluded_dependency_globs = ReactOnRailsPro.configuration.excluded_dependency_globs
      if excluded_dependency_globs.present?
        excluded_files = Dir.glob(excluded_dependency_globs).uniq
        files -= excluded_files
      end
      files.sort!

      digest = Digest::MD5.new
      files.each { |f| digest.file(f) unless File.directory?(f) }
      digest
    end

    # Returns a string which should be used as a component in any cache key for
    # react_component or react_component_hash when server rendering.
    # Value is either:
    # - the hashed server bundle filename (when no copied assets are configured), or
    # - an MD5 digest of server bundle contents plus copied asset contents.
    def self.bundle_hash
      return @bundle_hash if @bundle_hash && !(Rails.env.development? || Rails.env.test?)

      server_bundle_js_file_path = ReactOnRails::Utils.server_bundle_js_file_path
      asset_paths = bundle_hash_asset_paths

      hashed_file_name = hash_from_bundle_file_name(server_bundle_js_file_path, asset_paths)
      return @bundle_hash = hashed_file_name if hashed_file_name

      if contains_http_url?([server_bundle_js_file_path] + asset_paths)
        return @bundle_hash = calc_bundle_hash(server_bundle_js_file_path, asset_paths)
      end

      current_signature = bundle_hash_signature(server_bundle_js_file_path, asset_paths)
      return @bundle_hash if @bundle_hash && @bundle_hash_signature == current_signature

      next_hash = calc_bundle_hash(server_bundle_js_file_path, asset_paths)
      @bundle_hash = next_hash
      @bundle_hash_signature = current_signature
      @bundle_hash
    end

    def self.rsc_bundle_hash
      return @rsc_bundle_hash if @rsc_bundle_hash && !(Rails.env.development? || Rails.env.test?)

      server_rsc_bundle_js_file_path = rsc_bundle_js_file_path
      asset_paths = bundle_hash_asset_paths

      hashed_file_name = hash_from_bundle_file_name(server_rsc_bundle_js_file_path, asset_paths)
      return @rsc_bundle_hash = hashed_file_name if hashed_file_name

      if contains_http_url?([server_rsc_bundle_js_file_path] + asset_paths)
        return @rsc_bundle_hash = calc_bundle_hash(server_rsc_bundle_js_file_path, asset_paths)
      end

      current_signature = bundle_hash_signature(server_rsc_bundle_js_file_path, asset_paths)
      return @rsc_bundle_hash if @rsc_bundle_hash && @rsc_bundle_hash_signature == current_signature

      next_hash = calc_bundle_hash(server_rsc_bundle_js_file_path, asset_paths)
      @rsc_bundle_hash = next_hash
      @rsc_bundle_hash_signature = current_signature
      @rsc_bundle_hash
    end

    # Returns the hashed file name when using Shakapacker. Useful for creating cache keys.
    def self.bundle_file_name(bundle_name)
      # bundle_js_uri_from_packer can return a file path or a HTTP URL (for files served from the dev server)
      # Pathname can handle both cases
      full_path = ReactOnRails::PackerUtils.bundle_js_uri_from_packer(bundle_name)
      pathname = Pathname.new(full_path)
      pathname.basename.to_s
    end

    # Returns the hashed file name of the server bundle when using Shakapacker.
    # Necessary for fragment-caching keys.
    def self.server_bundle_file_name
      return @server_bundle_hash if @server_bundle_hash && !Rails.env.development?

      @server_bundle_hash = begin
        server_bundle_name = ReactOnRails.configuration.server_bundle_js_file
        bundle_file_name(server_bundle_name)
      end
    end

    def self.calc_bundle_hash(server_bundle_js_file_path, asset_paths = bundle_hash_asset_paths)
      digest = Digest::MD5.new
      # Include logical paths so different declared bundle/asset sets produce
      # different hashes even when some files are missing.
      digest << "bundle:#{digest_path_key(server_bundle_js_file_path)}\0"
      digest_bundle_content(digest, server_bundle_js_file_path)

      asset_paths.each do |asset_path|
        digest << "asset:#{digest_path_key(asset_path)}\0"
        digest_asset_content(digest, asset_path)
      end

      "#{digest.hexdigest}-#{Rails.env}"
    end

    def self.bundle_hash_signature(server_bundle_js_file_path, asset_paths)
      ([server_bundle_js_file_path.to_s] + asset_paths).map { |file_path| file_signature(file_path) }.join("\0")
    end

    def self.file_signature(file_path)
      path = file_path.to_s
      return "url:#{path}" if http_url?(path)
      return "missing:#{path}" unless File.exist?(path)
      return "dir:#{path}" if File.directory?(path)

      "#{path}:#{File.mtime(path).to_f}:#{File.size(path)}"
    end

    def self.hash_from_bundle_file_name(server_bundle_js_file_path, asset_paths)
      return nil unless asset_paths.empty?

      server_bundle_basename = Pathname.new(server_bundle_js_file_path).basename.to_s
      return nil unless contains_hash?(server_bundle_basename)

      server_bundle_basename
    end

    def self.digest_bundle_content(digest, bundle_path)
      if http_url?(bundle_path)
        digest << http_body_for_path(bundle_path)
      else
        return unless File.exist?(bundle_path)
        return if File.directory?(bundle_path)

        digest.file(bundle_path)
      end
    end

    def self.digest_path_key(file_path)
      path = file_path.to_s
      return path if http_url?(path)

      pathname = Pathname.new(path).cleanpath
      rails_root = Rails.root.to_s
      return pathname.to_s if rails_root.empty?

      root_pathname = Pathname.new(rails_root).cleanpath
      begin
        relative_path = pathname.relative_path_from(root_pathname).to_s
        return relative_path unless relative_path.start_with?("..#{File::SEPARATOR}") || relative_path == ".."
      rescue ArgumentError
        # Happens for unrelated roots (for example, different Windows drives).
      end

      pathname.to_s
    end

    def self.digest_asset_content(digest, asset_path)
      if http_url?(asset_path)
        digest << http_body_for_path(asset_path)
        return
      end

      return unless File.exist?(asset_path)
      return if File.directory?(asset_path)

      digest.file(asset_path)
    end

    def self.http_body_for_path(path)
      if Rails.env.production?
        raise ReactOnRailsPro::Error, "Not expected to get HTTP url for bundle or assets in production mode"
      end

      HTTPX.get(path).body.to_s
    end

    # TODO: Need to consider if the configuration value has the ".js" on the end.
    def self.contains_hash?(server_bundle_basename)
      ReactOnRails.configuration.server_bundle_js_file != server_bundle_basename &&
        ReactOnRailsPro.configuration.rsc_bundle_js_file != server_bundle_basename
    end

    def self.bundle_hash_asset_paths
      asset_paths = Array(ReactOnRailsPro.configuration.assets_to_copy).compact.map(&:to_s)

      if ReactOnRailsPro.configuration.enable_rsc_support
        asset_paths << react_client_manifest_file_path.to_s
        asset_paths << react_server_client_manifest_file_path.to_s
      end

      asset_paths.uniq.sort
    end

    def self.http_url?(path)
      path.to_s.match?(%r{\Ahttps?://}i)
    end

    def self.contains_http_url?(paths)
      paths.any? { |path| http_url?(path) }
    end

    def self.with_trace(message = nil)
      return yield unless ReactOnRailsPro.configuration.tracing && Rails.logger.info?

      start = Time.current
      result = yield
      finish = Time.current

      caller_method = caller(1..1).first[/[`'][^']*'/][1..-2]
      timing = "#{((finish - start) * 1_000).round(1)}ms"
      Rails.logger.info "[ReactOnRailsPro] PID:#{Process.pid} #{caller_method}: #{[message, timing].compact.join(', ')}"

      result
    end

    def self.common_form_data
      dependencies = if ReactOnRailsPro.configuration.enable_rsc_support
                       pool = ReactOnRailsPro::ServerRenderingPool::NodeRenderingPool
                       [pool.rsc_bundle_hash, pool.server_bundle_hash]
                     end

      {
        "gemVersion" => ReactOnRailsPro::VERSION,
        "protocolVersion" => ReactOnRailsPro::PROTOCOL_VERSION,
        "password" => ReactOnRailsPro.configuration.renderer_password,
        "dependencyBundleTimestamps" => dependencies,
        "railsEnv" => Rails.env.to_s
      }
    end

    def self.mine_type_from_file_name(filename)
      extension = File.extname(filename)
      Rack::Mime.mime_type(extension)
    end

    # TODO: write test
    def self.printable_cache_key(cache_key)
      cache_key.map do |key|
        if key.is_a?(Enumerable)
          printable_cache_key(key)
        elsif key.respond_to?(:cache_key_with_version)
          key.cache_key_with_version
        elsif key.respond_to?(:cache_key)
          key.cache_key
        else
          key.to_s
        end
      end.join("_").underscore
    end

    # Generates the Pro-specific HTML attribution comment based on license status
    # Called by React on Rails helper to generate license-specific attribution
    # Includes organization name when available (plan is only shown in server logs for privacy)
    def self.pro_attribution_comment
      base = "Powered by React on Rails Pro (c) ShakaCode"
      org = ReactOnRailsPro::LicenseValidator.license_organization

      comment = case ReactOnRailsPro::LicenseValidator.license_status
                when :valid
                  if org.present?
                    "#{base} | Licensed to #{org}"
                  else
                    "#{base} | Licensed"
                  end
                when :expired
                  "#{base} | LICENSE EXPIRED"
                when :invalid
                  "#{base} | INVALID LICENSE"
                when :missing
                  "#{base} | UNLICENSED"
                end

      "<!-- #{comment} -->"
    end

    # Returns license information for use in helpers and components
    # Delegates to LicenseValidator.license_info
    # @return [Hash] License info including org, plan, status, and attribution_required
    def self.license_info
      ReactOnRailsPro::LicenseValidator.license_info
    end
  end
end

# rubocop:enable Metrics/ModuleLength
