# frozen_string_literal: true

require "fileutils"
require "json"
require "pathname"
require "react_on_rails/error"
require "tempfile"

module ReactOnRails
  module TypeScriptResponseTypes
    DEFAULT_OUTPUT_PATH = "app/javascript/types/react_on_rails_response_types.d.ts"
    GENERATED_HEADER = "// Generated by react_on_rails:generate_response_types. Do not edit by hand."
    BOOLEAN_MODIFIER_VALUES = [true, false].freeze
    IDENTIFIER_PATTERN = /\A[$A-Z_a-z][$0-9A-Z_a-z]*\z/
    OPTION_KEYS = %i[array fields nullable optional raw type].freeze
    RAW_TYPE_GROUP_CLOSES = { "(" => ")", "[" => "]", "{" => "}", "<" => ">" }.freeze
    RAW_TYPE_GROUP_ENDS = RAW_TYPE_GROUP_CLOSES.values.freeze
    RAW_TYPE_STRING_LITERAL_PATTERN = /'(?:\\.|[^'\\])*'|"(?:\\.|[^"\\])*"|`(?:\\.|[^`\\])*`/
    RAW_TYPE_NESTING_TOKEN_PATTERN = /#{RAW_TYPE_STRING_LITERAL_PATTERN.source}|=>|[({\[<]|[)}\]>]|,/
    RAW_TYPE_UNSAFE_LINE_BREAK_PATTERN = /[\r\n\u2028\u2029]/
    RAW_TYPE_UNSAFE_NON_STRING_PATTERN = %r{;|//|/\*|\*/}
    REGISTRY_MUTEX = Mutex.new
    WRAPPER_TYPE_KEYS = %i[array fields raw type].freeze
    RESERVED_TYPE_NAMES = %w[
      abstract accessor any as asserts await bigint boolean break case catch class const continue debugger declare
      default delete do else enum export extends false finally for function global if implements import in infer
      instanceof interface is keyof let module namespace never new null number object override package private protected
      public
      readonly return satisfies static string super switch symbol this throw true try type typeof undefined unique
      unknown using var void while with yield
      AbortController Array ArrayBuffer ArrayBufferLike Awaited Blob Boolean Capitalize ConstructorParameters DataView
      Date Error EvalError Event EventTarget Exclude Extract File Float32Array Float64Array FormData Function Headers
      InstanceType Int8Array Int16Array Int32Array JSON Lowercase Map Math NonNullable Number Object Omit
      OmitThisParameter Parameters Partial Pick Promise RangeError Readonly ReadonlyArray Record ReferenceError RegExp
      Request Required Response ReturnType Set String SyntaxError ThisParameterType ThisType TypeError Uint8Array
      Uint8ClampedArray Uint16Array Uint32Array Uncapitalize URIError URL URLSearchParams Uppercase WeakMap WeakSet
    ].freeze
    GENERATED_TYPE_NAMES = %w[
      JsonValue RailsResponseTypes RailsResponseTypeName RailsResponseType
    ].freeze
    JSON_VALUE_DEFINITION = "export type JsonValue = " \
                            "string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };"
    SCALAR_TYPES = {
      any: "any",
      bool: "boolean",
      boolean: "boolean",
      # JSON responses serialize dates as strings; use raw: "Date" only for non-JSON values.
      date: "string",
      float: "number",
      integer: "number",
      json: "JsonValue",
      null: "null",
      number: "number",
      string: "string",
      unknown: "unknown"
    }.freeze

    Definition = Struct.new(:name, :fields, :response_key, keyword_init: true)
    private_constant :Definition, :REGISTRY_MUTEX

    module TypeSpecHelpers
      private

      def validate_fields!(fields)
        return if fields.is_a?(Hash)

        raise ReactOnRails::Error, "Response type fields must be a Hash, got #{fields.class}"
      end

      def unsafe_raw_type_expression?(expression)
        expression.match?(RAW_TYPE_UNSAFE_LINE_BREAK_PATTERN) ||
          expression.gsub(RAW_TYPE_STRING_LITERAL_PATTERN, "").match?(RAW_TYPE_UNSAFE_NON_STRING_PATTERN) ||
          unsafe_raw_type_nesting?(expression)
      end

      def unsafe_raw_type_nesting?(expression)
        expected_group_ends = []

        expression.scan(RAW_TYPE_NESTING_TOKEN_PATTERN) do |token|
          return true if unsafe_raw_type_nesting_token?(token, expected_group_ends)
        end

        expected_group_ends.any?
      end

      def unsafe_raw_type_nesting_token?(token, expected_group_ends)
        return true if token == "," && expected_group_ends.empty?

        group_end = RAW_TYPE_GROUP_CLOSES[token]
        if group_end
          expected_group_ends << group_end
          return false
        end

        return true if token == ">" && expected_group_ends.last != ">"
        return false unless RAW_TYPE_GROUP_ENDS.include?(token)

        expected_group_ends.pop != token
      end

      def wrapper_keys_for(normalized)
        WRAPPER_TYPE_KEYS.select { |key| normalized.key?(key) }
      end

      def validate_modifier_only_hash!(spec, normalized)
        return unless wrapper_keys_for(normalized).empty?
        return unless normalized.key?(:nullable) || normalized.key?(:optional)
        return unless non_option_keys_for(spec).empty?

        raise ReactOnRails::Error,
              "Modifier-only response type spec #{spec.inspect} must include :type, :array, :fields, or :raw"
      end

      def validate_modifier_booleans!(spec, normalized)
        return unless wrapper_keys_for(normalized).any? || non_option_keys_for(spec).empty?

        %i[nullable optional].each do |key|
          next unless normalized.key?(key)
          next if BOOLEAN_MODIFIER_VALUES.include?(normalized[key])

          raise ReactOnRails::Error,
                "Response type spec #{key.inspect} modifier must be true or false: #{spec.inspect}"
        end
      end

      def non_option_keys_for(spec)
        spec.filter_map do |key, _value|
          key = key.to_sym
          key unless OPTION_KEYS.include?(key)
        end
      end

      def unrecognized_option_keys_with_unsupported_values(spec)
        spec.filter_map do |key, value|
          key = key.to_sym
          next if OPTION_KEYS.include?(key) || plain_object_field_value?(value)

          key
        end
      end

      def plain_object_field_value?(value)
        value.is_a?(Array) || value.is_a?(Hash) || value.is_a?(String) || value.is_a?(Symbol)
      end

      def normalize_option_hash(spec)
        spec.each_with_object({}) do |(key, value), normalized|
          normalized[key.to_sym] = value if OPTION_KEYS.include?(key.to_sym)
        end
      end

      def raw_wrapper_hash?(spec)
        return false unless spec.is_a?(Hash)

        normalized = normalize_option_hash(spec)
        normalized.key?(:raw) && option_wrapper_hash?(spec, normalized)
      end

      def nullable_type(type, raw:)
        type = "(#{type})" if raw && raw_type_needs_parentheses_for_union?(type)
        "#{type} | null"
      end

      def raw_type(type)
        unless type.is_a?(String) && !type.strip.empty?
          raise ReactOnRails::Error, "Raw TypeScript type specs must be non-empty strings"
        end

        raw_expression = type.strip
        if unsafe_raw_type_expression?(raw_expression)
          raise ReactOnRails::Error, "Raw TypeScript type specs must be safe single-line type expressions"
        end

        raw_expression
      end

      def raw_type_needs_parentheses_for_union?(type)
        type.match?(/=>|\?/)
      end
    end

    class << self
      def define_type(type_name, fields:)
        REGISTRY_MUTEX.synchronize { current_registry.define_type(type_name, fields:) }
      end

      def define_response(response_key, type_name:, fields:)
        REGISTRY_MUTEX.synchronize { current_registry.define_response(response_key, type_name:, fields:) }
      end

      def generate(output_path: nil)
        path = root_relative_output_path(output_path || DEFAULT_OUTPUT_PATH)
        content = to_d_ts
        write_generated_file(path, content)
        path.to_s
      end

      def to_d_ts
        REGISTRY_MUTEX.synchronize { Emitter.new(current_registry).to_d_ts }
      end

      def reset!
        REGISTRY_MUTEX.synchronize { @current_registry = Registry.new }
      end

      def registry
        REGISTRY_MUTEX.synchronize { current_registry }
      end

      private

      def current_registry
        @current_registry ||= Registry.new
      end

      def root_relative_output_path(output_path)
        path = Pathname.new(output_path)
        path = Rails.root.join(path) unless path.absolute?

        expanded_path = path.expand_path
        expanded_root = Rails.root.expand_path
        real_root = expanded_root.realpath
        real_parent = nearest_existing_path(expanded_path).realpath
        if !root_path?(expanded_path, expanded_root, real_root) && same_or_child_path?(real_parent, real_root)
          output_path_error!(output_path) if expanded_path.directory?

          return expanded_path
        end

        output_path_error!(output_path)
      rescue ArgumentError, Errno::ENOENT, Errno::ELOOP, Errno::ENOTDIR, Errno::EINVAL, Errno::EACCES, Errno::EPERM
        output_path_error!(output_path)
      end

      def write_generated_file(path, content)
        cleanup_directory = highest_missing_ancestor(path.dirname)
        FileUtils.mkdir_p(path.dirname)
        validate_generated_file_parent!(path)
        tempfile = Tempfile.new([".react_on_rails_types", ".tmp"], path.dirname)
        tempfile.write(content)
        tempfile.close
        FileUtils.mv(tempfile.path, path.to_s)
      rescue StandardError
        cleanup_tempfile(tempfile)
        FileUtils.rm_rf(cleanup_directory) if cleanup_directory&.exist?
        raise
      end

      def cleanup_tempfile(tempfile)
        return unless tempfile

        tempfile.close unless tempfile.closed?
        tempfile.unlink if tempfile.path && File.exist?(tempfile.path)
      end

      def highest_missing_ancestor(path)
        missing_path = nil
        current_path = path

        until current_path.exist? || current_path.symlink?
          missing_path = current_path
          parent_path = current_path.dirname
          break if parent_path == current_path

          current_path = parent_path
        end

        missing_path
      end

      def validate_generated_file_parent!(path)
        real_root = Rails.root.expand_path.realpath
        real_parent = path.dirname.realpath
        return if same_or_child_path?(real_parent, real_root)

        output_path_error!(path.to_s)
      rescue ArgumentError, Errno::ENOENT, Errno::ELOOP, Errno::ENOTDIR, Errno::EINVAL, Errno::EACCES, Errno::EPERM
        output_path_error!(path.to_s)
      end

      def nearest_existing_path(path)
        current_path = path
        until current_path.exist? || current_path.symlink?
          parent_path = current_path.dirname
          return parent_path if parent_path == current_path

          current_path = parent_path
        end
        current_path
      end

      def child_path?(path, parent_path)
        path.to_s.start_with?("#{parent_path}#{File::SEPARATOR}")
      end

      def same_or_child_path?(path, parent_path)
        path.to_s == parent_path.to_s || child_path?(path, parent_path)
      end

      def output_path_error!(output_path)
        raise ReactOnRails::Error, "Response types output path must be inside Rails.root: #{output_path.inspect}"
      end

      def root_path?(path, expanded_root, real_root)
        return true if path.to_s == expanded_root.to_s

        path.exist? && path.realpath.to_s == real_root.to_s
      end
    end

    class Registry
      include TypeSpecHelpers

      attr_reader :types, :responses

      def initialize
        @types = []
        @responses = []
        @mutex = Mutex.new
      end

      def define_type(type_name, fields:)
        @mutex.synchronize do
          name = normalize_type_name(type_name)
          validate_fields!(fields)
          ensure_unique_type_name!(name)
          @types << Definition.new(name:, fields:, response_key: nil)
        end
      end

      def define_response(response_key, type_name:, fields:)
        @mutex.synchronize do
          key = response_key.to_s.strip
          validate_response_key!(key)
          name = normalize_type_name(type_name)
          validate_fields!(fields)
          ensure_unique_response_key!(key)
          ensure_unique_type_name!(name)
          @responses << Definition.new(name:, fields:, response_key: key)
        end
      end

      private

      def normalize_type_name(type_name)
        name = type_name.to_s
        unless name.match?(IDENTIFIER_PATTERN)
          raise ReactOnRails::Error, "TypeScript type name must be a valid identifier: #{type_name.inspect}"
        end

        raise ReactOnRails::Error, "TypeScript type name is reserved: #{type_name.inspect}" if reserved_type_name?(name)

        name
      end

      def reserved_type_name?(type_name)
        RESERVED_TYPE_NAMES.include?(type_name) || GENERATED_TYPE_NAMES.include?(type_name)
      end

      def ensure_unique_type_name!(type_name)
        return unless definitions.any? { |definition| definition.name == type_name }

        raise ReactOnRails::Error, "Duplicate TypeScript type name: #{type_name}"
      end

      def ensure_unique_response_key!(response_key)
        return unless @responses.any? { |response| response.response_key == response_key }

        raise ReactOnRails::Error, "Duplicate response type key: #{response_key}"
      end

      def validate_response_key!(response_key)
        return unless response_key.strip.empty?

        raise ReactOnRails::Error, "Response type key must be present"
      end

      def definitions
        @types + @responses
      end
    end

    class Emitter
      include TypeSpecHelpers

      def initialize(registry)
        @registry = registry
      end

      def to_d_ts
        lines = [GENERATED_HEADER, "", JSON_VALUE_DEFINITION]
        definitions.each { |definition| lines.push("", interface_definition(definition)) }
        lines.push("", response_map_definition)
        lines.push("", response_helpers) unless registry.responses.empty?
        "#{lines.join("\n")}\n"
      end

      private

      attr_reader :registry

      def definitions
        registry.types + registry.responses
      end

      def interface_definition(definition)
        body = fields_to_lines(definition.fields, indentation: "  ")
        return "export interface #{definition.name} {}" if body.empty?

        "export interface #{definition.name} {\n#{body.join("\n")}\n}"
      end

      def response_map_definition
        return "export interface RailsResponseTypes {}" if registry.responses.empty?

        body = registry.responses.map do |response|
          "  #{quote_property(response.response_key)}: #{response.name};"
        end
        "export interface RailsResponseTypes {\n#{body.join("\n")}\n}"
      end

      def response_helpers
        <<~TS.chomp
          export type RailsResponseTypeName = keyof RailsResponseTypes;
          export type RailsResponseType<TName extends RailsResponseTypeName> = RailsResponseTypes[TName];
        TS
      end

      def fields_to_lines(fields, indentation:)
        validate_fields!(fields)

        fields.map do |field_name, spec|
          options = options_for(spec)
          type = render_type(spec, indentation: "#{indentation}  ", closing_indentation: indentation)
          type = nullable_type(type, raw: raw_wrapper_hash?(spec)) if options.fetch(:nullable, false)
          suffix = options.fetch(:optional, false) ? "?" : ""
          "#{indentation}#{quote_property(field_name)}#{suffix}: #{type};"
        end
      end

      def render_type(spec, indentation:, closing_indentation:)
        case spec
        when Array
          raise ReactOnRails::Error, "Array type specs must contain exactly one member" unless spec.length == 1

          array_type(spec.first, indentation:, closing_indentation:)
        when Hash
          render_hash_type(spec, indentation:, closing_indentation:)
        when Symbol, String
          render_named_type(spec)
        else
          raise ReactOnRails::Error, "Unsupported response type spec: #{spec.inspect}"
        end
      end

      def render_hash_type(spec, indentation:, closing_indentation:)
        normalized = normalize_option_hash(spec)
        validate_modifier_booleans!(spec, normalized)
        validate_modifier_only_hash!(spec, normalized)

        if option_wrapper_hash?(spec, normalized)
          return array_type(normalized.fetch(:array), indentation:, closing_indentation:) if normalized.key?(:array)
          return raw_type(normalized.fetch(:raw)) if normalized.key?(:raw)
          return render_type(normalized.fetch(:type), indentation:, closing_indentation:) if normalized.key?(:type)

          return object_type(normalized.fetch(:fields), indentation:, closing_indentation:)
        end

        object_type(spec, indentation:, closing_indentation:)
      end

      def object_type(fields, indentation:, closing_indentation:)
        body = fields_to_lines(fields, indentation:)
        return "{}" if body.empty?

        "{\n#{body.join("\n")}\n#{closing_indentation}}"
      end

      def array_type(member_spec, indentation:, closing_indentation:)
        member_options = options_for(member_spec)
        if member_options.fetch(:optional, false)
          raise ReactOnRails::Error,
                "optional: is not valid inside an array member spec because array elements cannot be optional"
        end

        member_type = render_type(member_spec, indentation:, closing_indentation:)
        raw_member = raw_wrapper_hash?(member_spec)
        member_type = nullable_type(member_type, raw: raw_member) if member_options.fetch(:nullable, false)
        member_type = "(#{member_type})" if raw_member || member_type.match?(/[\n|&]|=>|\?/)
        "#{member_type}[]"
      end

      def render_named_type(name)
        if name.is_a?(Symbol)
          scalar_type = SCALAR_TYPES[name]
          return scalar_type if scalar_type

          raise ReactOnRails::Error, "Unknown scalar response type alias: #{name.inspect}"
        end

        type_name = name.to_s
        unless type_name.match?(IDENTIFIER_PATTERN)
          raise ReactOnRails::Error, "TypeScript type reference must be a valid identifier: #{name.inspect}"
        end

        return type_name if definitions.any? { |definition| definition.name == type_name }

        raise ReactOnRails::Error, "Unknown TypeScript type reference: #{name.inspect}"
      end

      def options_for(spec)
        return {} unless spec.is_a?(Hash)

        normalized = normalize_option_hash(spec)
        validate_modifier_booleans!(spec, normalized)
        return {} unless option_wrapper_hash?(spec, normalized)

        {
          nullable: normalized.fetch(:nullable, false),
          optional: normalized.fetch(:optional, false)
        }
      end

      def option_wrapper_hash?(spec, normalized = nil)
        return false unless spec.is_a?(Hash)

        normalized ||= normalize_option_hash(spec)
        wrapper_keys = wrapper_keys_for(normalized)

        non_option_keys = non_option_keys_for(spec)
        if non_option_keys.any?
          validate_non_option_wrapper_keys!(spec, normalized, wrapper_keys, non_option_keys)
          return false
        end

        return false if wrapper_keys.empty?
        return true if wrapper_keys.one?

        raise ReactOnRails::Error, "Response type specs can only use one of :array, :fields, :raw, or :type"
      end

      def validate_non_option_wrapper_keys!(spec, normalized, wrapper_keys, non_option_keys)
        if wrapper_keys.any? && (normalized.key?(:nullable) || normalized.key?(:optional))
          raise ReactOnRails::Error,
                "Unrecognized option key(s) in response type spec: #{non_option_keys.map(&:inspect).join(', ')}"
        end

        validate_wrapper_option_keys!(spec, wrapper_keys)
      end

      def validate_wrapper_option_keys!(spec, wrapper_keys)
        return if wrapper_keys.empty?

        unrecognized_keys = unrecognized_option_keys_with_unsupported_values(spec)
        return if unrecognized_keys.empty?

        raise ReactOnRails::Error,
              "Unrecognized option key(s) in response type spec: #{unrecognized_keys.map(&:inspect).join(', ')}"
      end

      def quote_property(property_name)
        name = property_name.to_s
        return name if name.match?(IDENTIFIER_PATTERN)

        name.to_json
      end
    end
  end
end
