# frozen_string_literal: true

require "fileutils"
require "json"
require "pathname"

module ReactOnRails
  module TypeScriptResponseTypes
    DEFAULT_OUTPUT_PATH = "app/javascript/generated/react_on_rails_response_types.d.ts"
    GENERATED_HEADER = "// Generated by react_on_rails:generate_response_types. Do not edit by hand."
    IDENTIFIER_PATTERN = /\A[$A-Z_a-z][$0-9A-Z_a-z]*\z/
    OPTION_KEYS = %i[array fields nullable optional type].freeze
    RESERVED_TYPE_NAMES = %w[
      any as await boolean break case catch class const continue debugger default delete do else enum export extends
      false finally for function if implements import in instanceof interface let namespace never new null number object
      package private protected public return static string super switch symbol this throw true try typeof undefined
      unknown var void while with yield
    ].freeze
    GENERATED_TYPE_NAMES = %w[
      JsonValue RailsResponseTypes RailsResponseTypeName RailsResponseType
    ].freeze
    SCALAR_TYPES = {
      any: "any",
      bool: "boolean",
      boolean: "boolean",
      date: "string",
      float: "number",
      integer: "number",
      json: "JsonValue",
      null: "null",
      number: "number",
      string: "string",
      unknown: "unknown"
    }.freeze

    Definition = Struct.new(:name, :fields, :response_key, keyword_init: true)

    class << self
      def define_type(type_name, fields:)
        registry.define_type(type_name, fields:)
      end

      def define_response(response_key, type_name:, fields:)
        registry.define_response(response_key, type_name:, fields:)
      end

      def generate(output_path: nil)
        path = Pathname.new(output_path || default_output_path)
        FileUtils.mkdir_p(path.dirname)
        File.write(path, to_d_ts)
        path.to_s
      end

      def to_d_ts
        Emitter.new(registry).to_d_ts
      end

      def reset!
        @registry = Registry.new
      end

      def registry
        @registry ||= Registry.new
      end

      private

      def default_output_path
        Rails.root.join(DEFAULT_OUTPUT_PATH)
      end
    end

    class Registry
      attr_reader :types, :responses

      def initialize
        @types = []
        @responses = []
      end

      def define_type(type_name, fields:)
        name = normalize_type_name(type_name)
        ensure_unique_type_name!(name)
        @types << Definition.new(name:, fields:, response_key: nil)
      end

      def define_response(response_key, type_name:, fields:)
        key = response_key.to_s
        name = normalize_type_name(type_name)
        ensure_unique_response_key!(key)
        ensure_unique_type_name!(name)
        @responses << Definition.new(name:, fields:, response_key: key)
      end

      private

      def normalize_type_name(type_name)
        name = type_name.to_s
        return name if name.match?(IDENTIFIER_PATTERN) && !reserved_type_name?(name)

        raise ReactOnRails::Error, "TypeScript type name must be a valid identifier: #{type_name.inspect}"
      end

      def reserved_type_name?(type_name)
        RESERVED_TYPE_NAMES.include?(type_name) || GENERATED_TYPE_NAMES.include?(type_name)
      end

      def ensure_unique_type_name!(type_name)
        return unless definitions.any? { |definition| definition.name == type_name }

        raise ReactOnRails::Error, "Duplicate TypeScript type name: #{type_name}"
      end

      def ensure_unique_response_key!(response_key)
        return unless @responses.any? { |response| response.response_key == response_key }

        raise ReactOnRails::Error, "Duplicate response type key: #{response_key}"
      end

      def definitions
        @types + @responses
      end
    end

    class Emitter
      def initialize(registry)
        @registry = registry
      end

      def to_d_ts
        lines = [GENERATED_HEADER, "", json_value_definition]
        definitions.each { |definition| lines.push("", interface_definition(definition)) }
        lines.push("", response_map_definition, "", response_helpers)
        "#{lines.join("\n")}\n"
      end

      private

      attr_reader :registry

      def definitions
        registry.types + registry.responses
      end

      def json_value_definition
        "export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };"
      end

      def interface_definition(definition)
        body = fields_to_lines(definition.fields, indentation: "  ")
        return "export interface #{definition.name} {}" if body.empty?

        "export interface #{definition.name} {\n#{body.join("\n")}\n}"
      end

      def response_map_definition
        return "export interface RailsResponseTypes {}" if registry.responses.empty?

        body = registry.responses.map do |response|
          "  #{quote_property(response.response_key)}: #{response.name};"
        end
        "export interface RailsResponseTypes {\n#{body.join("\n")}\n}"
      end

      def response_helpers
        <<~TS.chomp
          export type RailsResponseTypeName = keyof RailsResponseTypes;
          export type RailsResponseType<TName extends RailsResponseTypeName> = RailsResponseTypes[TName];
        TS
      end

      def fields_to_lines(fields, indentation:)
        validate_fields!(fields)

        fields.map do |field_name, spec|
          options = options_for(spec)
          type = render_type(spec, indentation: "#{indentation}  ", closing_indentation: indentation)
          type = "#{type} | null" if options.fetch(:nullable, false)
          suffix = options.fetch(:optional, false) ? "?" : ""
          "#{indentation}#{quote_property(field_name)}#{suffix}: #{type};"
        end
      end

      def render_type(spec, indentation:, closing_indentation:)
        case spec
        when Array
          raise ReactOnRails::Error, "Array type specs must contain exactly one member" unless spec.length == 1

          array_type(spec.first, indentation:, closing_indentation:)
        when Hash
          render_hash_type(spec, indentation:, closing_indentation:)
        when Symbol, String
          render_named_type(spec)
        else
          raise ReactOnRails::Error, "Unsupported response type spec: #{spec.inspect}"
        end
      end

      def render_hash_type(spec, indentation:, closing_indentation:)
        normalized = normalize_option_hash(spec)

        if option_wrapper_hash?(spec, normalized)
          return array_type(normalized.fetch(:array), indentation:, closing_indentation:) if normalized.key?(:array)
          return render_type(normalized.fetch(:type), indentation:, closing_indentation:) if normalized.key?(:type)

          return object_type(normalized.fetch(:fields), indentation:, closing_indentation:)
        end

        object_type(spec, indentation:, closing_indentation:)
      end

      def object_type(fields, indentation:, closing_indentation:)
        body = fields_to_lines(fields, indentation:)
        return "{}" if body.empty?

        "{\n#{body.join("\n")}\n#{closing_indentation}}"
      end

      def array_type(member_spec, indentation:, closing_indentation:)
        member_type = render_type(member_spec, indentation:, closing_indentation:)
        member_options = options_for(member_spec)
        member_type = "#{member_type} | null" if member_options.fetch(:nullable, false)
        member_type = "(#{member_type})" if member_type.include?("\n") || member_type.include?(" | ")
        "#{member_type}[]"
      end

      def render_named_type(name)
        scalar_type = SCALAR_TYPES[name.to_s.downcase.to_sym] if name.is_a?(Symbol)
        return scalar_type if scalar_type

        type_name = name.to_s
        return type_name if type_name.match?(IDENTIFIER_PATTERN)

        raise ReactOnRails::Error, "TypeScript type reference must be a valid identifier: #{name.inspect}"
      end

      def options_for(spec)
        return {} unless spec.is_a?(Hash)

        normalized = normalize_option_hash(spec)
        return {} unless option_wrapper_hash?(spec, normalized)

        {
          nullable: normalized.fetch(:nullable, false),
          optional: normalized.fetch(:optional, false)
        }
      end

      def option_wrapper_hash?(spec, normalized = nil)
        return false unless spec.is_a?(Hash)

        normalized ||= normalize_option_hash(spec)
        has_wrapper_type = normalized.key?(:array) || normalized.key?(:fields) || normalized.key?(:type)
        has_wrapper_type && normalized.length == spec.length
      end

      def normalize_option_hash(spec)
        spec.each_with_object({}) do |(key, value), normalized|
          normalized[key.to_sym] = value if OPTION_KEYS.include?(key.to_sym)
        end
      end

      def validate_fields!(fields)
        return if fields.is_a?(Hash)

        raise ReactOnRails::Error, "Response type fields must be a Hash, got #{fields.class}"
      end

      def quote_property(property_name)
        name = property_name.to_s
        return name if name.match?(IDENTIFIER_PATTERN)

        name.to_json
      end
    end
  end
end
