# frozen_string_literal: true

require "fileutils"
require "json"
require "pathname"

module ReactOnRails
  module TypeScriptResponseTypes
    DEFAULT_OUTPUT_PATH = "app/javascript/types/react_on_rails_response_types.d.ts"
    GENERATED_HEADER = "// Generated by react_on_rails:generate_response_types. Do not edit by hand."
    IDENTIFIER_PATTERN = /\A[$A-Z_a-z][$0-9A-Z_a-z]*\z/
    OPTION_KEYS = %i[array fields nullable optional raw type].freeze
    WRAPPER_TYPE_KEYS = %i[array fields raw type].freeze
    RESERVED_TYPE_NAMES = %w[
      abstract accessor any as asserts await boolean break case catch class const continue debugger declare default
      delete do else enum export extends false finally for function global if implements import in infer instanceof
      interface is keyof let module namespace never new null number object override package private protected public
      readonly return satisfies static string super switch symbol this throw true try type typeof undefined unique
      unknown using var void while with yield
    ].freeze
    GENERATED_TYPE_NAMES = %w[
      JsonValue RailsResponseTypes RailsResponseTypeName RailsResponseType
    ].freeze
    SCALAR_TYPES = {
      any: "any",
      bool: "boolean",
      boolean: "boolean",
      date: "string",
      float: "number",
      integer: "number",
      json: "JsonValue",
      null: "null",
      number: "number",
      string: "string",
      unknown: "unknown"
    }.freeze

    Definition = Struct.new(:name, :fields, :response_key, keyword_init: true)

    class << self
      def define_type(type_name, fields:)
        registry.define_type(type_name, fields:)
      end

      def define_response(response_key, type_name:, fields:)
        registry.define_response(response_key, type_name:, fields:)
      end

      def generate(output_path: nil)
        path = root_relative_output_path(output_path || DEFAULT_OUTPUT_PATH)
        FileUtils.mkdir_p(path.dirname)
        File.write(path, to_d_ts)
        path.to_s
      end

      def to_d_ts
        Emitter.new(registry).to_d_ts
      end

      def reset!
        @registry = Registry.new
      end

      def registry
        @registry ||= Registry.new
      end

      private

      def root_relative_output_path(output_path)
        path = Pathname.new(output_path)
        path = Rails.root.join(path) unless path.absolute?

        expanded_path = path.expand_path
        expanded_root = Rails.root.expand_path
        real_root = expanded_root.realpath
        real_parent = nearest_existing_path(expanded_path).realpath
        return expanded_path if child_path?(expanded_path, expanded_root) && same_or_child_path?(real_parent, real_root)

        output_path_error!(output_path)
      rescue Errno::ENOENT, Errno::ELOOP, Errno::ENOTDIR, Errno::EINVAL, Errno::EACCES, Errno::EPERM
        output_path_error!(output_path)
      end

      def nearest_existing_path(path)
        current_path = path
        until current_path.exist? || current_path.symlink?
          parent_path = current_path.dirname
          return parent_path if parent_path == current_path

          current_path = parent_path
        end
        current_path
      end

      def child_path?(path, parent_path)
        path.to_s.start_with?("#{parent_path}#{File::SEPARATOR}")
      end

      def same_or_child_path?(path, parent_path)
        path.to_s == parent_path.to_s || child_path?(path, parent_path)
      end

      def output_path_error!(output_path)
        raise ReactOnRails::Error, "Response types output path must be inside Rails.root: #{output_path.inspect}"
      end
    end

    class Registry
      attr_reader :types, :responses

      def initialize
        @types = []
        @responses = []
      end

      def define_type(type_name, fields:)
        name = normalize_type_name(type_name)
        validate_fields!(fields)
        ensure_unique_type_name!(name)
        @types << Definition.new(name:, fields:, response_key: nil)
      end

      def define_response(response_key, type_name:, fields:)
        key = response_key.to_s
        name = normalize_type_name(type_name)
        validate_fields!(fields)
        ensure_unique_response_key!(key)
        ensure_unique_type_name!(name)
        @responses << Definition.new(name:, fields:, response_key: key)
      end

      private

      def normalize_type_name(type_name)
        name = type_name.to_s
        unless name.match?(IDENTIFIER_PATTERN)
          raise ReactOnRails::Error, "TypeScript type name must be a valid identifier: #{type_name.inspect}"
        end

        raise ReactOnRails::Error, "TypeScript type name is reserved: #{type_name.inspect}" if reserved_type_name?(name)

        name
      end

      def reserved_type_name?(type_name)
        RESERVED_TYPE_NAMES.include?(type_name) || GENERATED_TYPE_NAMES.include?(type_name)
      end

      def validate_fields!(fields)
        return if fields.is_a?(Hash)

        raise ReactOnRails::Error, "Response type fields must be a Hash, got #{fields.class}"
      end

      def ensure_unique_type_name!(type_name)
        return unless definitions.any? { |definition| definition.name == type_name }

        raise ReactOnRails::Error, "Duplicate TypeScript type name: #{type_name}"
      end

      def ensure_unique_response_key!(response_key)
        return unless @responses.any? { |response| response.response_key == response_key }

        raise ReactOnRails::Error, "Duplicate response type key: #{response_key}"
      end

      def definitions
        @types + @responses
      end
    end

    class Emitter
      def initialize(registry)
        @registry = registry
      end

      def to_d_ts
        lines = [GENERATED_HEADER, "", json_value_definition]
        definitions.each { |definition| lines.push("", interface_definition(definition)) }
        lines.push("", response_map_definition)
        lines.push("", response_helpers) unless registry.responses.empty?
        "#{lines.join("\n")}\n"
      end

      private

      attr_reader :registry

      def definitions
        registry.types + registry.responses
      end

      def json_value_definition
        "export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };"
      end

      def interface_definition(definition)
        body = fields_to_lines(definition.fields, indentation: "  ")
        return "export interface #{definition.name} {}" if body.empty?

        "export interface #{definition.name} {\n#{body.join("\n")}\n}"
      end

      def response_map_definition
        return "export interface RailsResponseTypes {}" if registry.responses.empty?

        body = registry.responses.map do |response|
          "  #{quote_property(response.response_key)}: #{response.name};"
        end
        "export interface RailsResponseTypes {\n#{body.join("\n")}\n}"
      end

      def response_helpers
        <<~TS.chomp
          export type RailsResponseTypeName = keyof RailsResponseTypes;
          export type RailsResponseType<TName extends RailsResponseTypeName> = RailsResponseTypes[TName];
        TS
      end

      def fields_to_lines(fields, indentation:)
        validate_fields!(fields)

        fields.map do |field_name, spec|
          options = options_for(spec)
          type = render_type(spec, indentation: "#{indentation}  ", closing_indentation: indentation)
          type = "#{type} | null" if options.fetch(:nullable, false)
          suffix = options.fetch(:optional, false) ? "?" : ""
          "#{indentation}#{quote_property(field_name)}#{suffix}: #{type};"
        end
      end

      def render_type(spec, indentation:, closing_indentation:)
        case spec
        when Array
          raise ReactOnRails::Error, "Array type specs must contain exactly one member" unless spec.length == 1

          array_type(spec.first, indentation:, closing_indentation:)
        when Hash
          render_hash_type(spec, indentation:, closing_indentation:)
        when Symbol, String
          render_named_type(spec)
        else
          raise ReactOnRails::Error, "Unsupported response type spec: #{spec.inspect}"
        end
      end

      def render_hash_type(spec, indentation:, closing_indentation:)
        normalized = normalize_option_hash(spec)

        if option_wrapper_hash?(spec, normalized)
          return array_type(normalized.fetch(:array), indentation:, closing_indentation:) if normalized.key?(:array)
          return raw_type(normalized.fetch(:raw)) if normalized.key?(:raw)
          return render_type(normalized.fetch(:type), indentation:, closing_indentation:) if normalized.key?(:type)

          return object_type(normalized.fetch(:fields), indentation:, closing_indentation:)
        end

        object_type(spec, indentation:, closing_indentation:)
      end

      def object_type(fields, indentation:, closing_indentation:)
        body = fields_to_lines(fields, indentation:)
        return "{}" if body.empty?

        "{\n#{body.join("\n")}\n#{closing_indentation}}"
      end

      def array_type(member_spec, indentation:, closing_indentation:)
        member_options = options_for(member_spec)
        if member_options.fetch(:optional, false)
          raise ReactOnRails::Error,
                "optional: is not valid inside an array member spec because array elements cannot be optional"
        end

        member_type = render_type(member_spec, indentation:, closing_indentation:)
        member_type = "#{member_type} | null" if member_options.fetch(:nullable, false)
        member_type = "(#{member_type})" if member_type.match?(/[\n|&]|=>|\s\?\s/)
        "#{member_type}[]"
      end

      def raw_type(type)
        unless type.is_a?(String) && !type.strip.empty?
          raise ReactOnRails::Error, "Raw TypeScript type specs must be non-empty strings"
        end

        raw_expression = type.strip
        if raw_expression.match?(/[\r\n;]/)
          raise ReactOnRails::Error, "Raw TypeScript type specs must be single-line type expressions"
        end

        raw_expression
      end

      def render_named_type(name)
        if name.is_a?(Symbol)
          scalar_type = SCALAR_TYPES[name]
          return scalar_type if scalar_type

          raise ReactOnRails::Error, "Unknown scalar response type alias: #{name.inspect}"
        end

        type_name = name.to_s
        unless type_name.match?(IDENTIFIER_PATTERN)
          raise ReactOnRails::Error, "TypeScript type reference must be a valid identifier: #{name.inspect}"
        end

        return type_name if definitions.any? { |definition| definition.name == type_name }

        raise ReactOnRails::Error, "Unknown TypeScript type reference: #{name.inspect}"
      end

      def options_for(spec)
        return {} unless spec.is_a?(Hash)

        normalized = normalize_option_hash(spec)
        return {} unless option_wrapper_hash?(spec, normalized)

        {
          nullable: normalized.fetch(:nullable, false),
          optional: normalized.fetch(:optional, false)
        }
      end

      def option_wrapper_hash?(spec, normalized = nil)
        return false unless spec.is_a?(Hash)

        normalized ||= normalize_option_hash(spec)
        wrapper_keys = wrapper_keys_for(normalized)
        validate_wrapper_option_keys!(spec, wrapper_keys)

        return false unless normalized.length == spec.length

        return false if wrapper_keys.empty?
        return true if wrapper_keys.one?

        raise ReactOnRails::Error, "Response type specs can only use one of :array, :fields, :raw, or :type"
      end

      def wrapper_keys_for(normalized)
        WRAPPER_TYPE_KEYS.select { |key| normalized.key?(key) }
      end

      def validate_wrapper_option_keys!(spec, wrapper_keys)
        unrecognized_keys = spec.keys.map(&:to_sym) - OPTION_KEYS
        return unless wrapper_keys.one? && unrecognized_keys.any?

        raise ReactOnRails::Error,
              "Unrecognized option key(s) in response type spec: #{unrecognized_keys.map(&:inspect).join(', ')}"
      end

      def normalize_option_hash(spec)
        spec.each_with_object({}) do |(key, value), normalized|
          normalized[key.to_sym] = value if OPTION_KEYS.include?(key.to_sym)
        end
      end

      def validate_fields!(fields)
        return if fields.is_a?(Hash)

        raise ReactOnRails::Error, "Response type fields must be a Hash, got #{fields.class}"
      end

      def quote_property(property_name)
        name = property_name.to_s
        return name if name.match?(IDENTIFIER_PATTERN)

        name.to_json
      end
    end
  end
end
