# frozen_string_literal: true

require "rails/generators"
require "fileutils"
require "erb"
require_relative "generator_messages"
require_relative "generator_helper"
require_relative "js_dependency_manager"
module ReactOnRails
  module Generators
    class BaseGenerator < Rails::Generators::Base
      include GeneratorHelper
      include JsDependencyManager

      Rails::Generators.hide_namespace(namespace)
      source_root(File.expand_path("templates", __dir__))

      # --redux
      class_option :redux,
                   type: :boolean,
                   default: false,
                   desc: "Install Redux package and Redux version of Hello World Example",
                   aliases: "-R"

      # --rspack
      class_option :rspack,
                   type: :boolean,
                   default: false,
                   desc: "Use Rspack instead of Webpack as the bundler"

      # --pro
      class_option :pro,
                   type: :boolean,
                   default: false,
                   desc: "Setup React on Rails Pro with Node Renderer"

      # --rsc
      class_option :rsc,
                   type: :boolean,
                   default: false,
                   desc: "Setup React Server Components (requires Pro)"

      # Hidden option: signals that Shakapacker was just installed by install_generator.
      # When true, copy_packer_config uses force: true to overwrite Shakapacker's default config
      # without prompting, since we know it's a fresh default (not user-customized).
      class_option :shakapacker_just_installed,
                   type: :boolean,
                   default: false,
                   hide: true

      # Keep this map in sync with templates under:
      # lib/generators/react_on_rails/templates/**/config/webpack/*.tt
      MANAGED_WEBPACK_FILE_TEMPLATES = {
        "clientWebpackConfig.js" => "base/base/config/webpack/clientWebpackConfig.js.tt",
        "commonWebpackConfig.js" => "base/base/config/webpack/commonWebpackConfig.js.tt",
        "test.js" => "base/base/config/webpack/test.js.tt",
        "development.js" => "base/base/config/webpack/development.js.tt",
        "production.js" => "base/base/config/webpack/production.js.tt",
        "serverWebpackConfig.js" => "base/base/config/webpack/serverWebpackConfig.js.tt",
        "rscWebpackConfig.js" => "rsc/base/config/webpack/rscWebpackConfig.js.tt",
        "ServerClientOrBoth.js" => "base/base/config/webpack/ServerClientOrBoth.js.tt",
        # Legacy filename generated by older React on Rails versions.
        # We compare against the current options (including --pro/--rsc); if those
        # don't match the original generation, cleanup intentionally preserves files.
        "generateWebpackConfigs.js" => "base/base/config/webpack/ServerClientOrBoth.js.tt"
      }.freeze

      # Keep these helper delegates in sync with ERB calls in managed webpack
      # templates. This is the intended template-facing API; missing delegates
      # intentionally fail rendering and keep cleanup conservative by treating
      # files as non-removable.
      TemplateRenderContext = Struct.new(:generator, :config) do
        def erb_binding
          binding
        end

        def add_documentation_reference(*args)
          generator.__send__(:add_documentation_reference, *args)
        end

        def use_pro?
          generator.__send__(:use_pro?)
        end

        def use_rsc?
          generator.__send__(:use_rsc?)
        end

        def shakapacker_version_9_or_higher?
          generator.__send__(:shakapacker_version_9_or_higher?)
        end
      end

      REMOVABLE_WEBPACK_FILES = (MANAGED_WEBPACK_FILE_TEMPLATES.keys +
        %w[webpack.config.js]).freeze
      DOCS_REFERENCE_MESSAGE = "// The source code including full typescript support is available at:"
      TEMPLATE_RENDER_FAILED = Object.new.freeze # unique sentinel compared by identity via .equal?
      private_constant :MANAGED_WEBPACK_FILE_TEMPLATES, :REMOVABLE_WEBPACK_FILES, :TemplateRenderContext,
                       :DOCS_REFERENCE_MESSAGE, :TEMPLATE_RENDER_FAILED

      def add_hello_world_route
        # RSC uses HelloServer instead of HelloWorld, but Redux still needs hello_world route
        return if use_rsc? && !options.redux?

        route "get 'hello_world', to: 'hello_world#index'"
      end

      def create_react_directories
        # Skip HelloWorld directory for Redux (uses HelloWorldApp) or RSC (uses HelloServer)
        return if options.redux? || use_rsc?

        empty_directory("app/javascript/src/HelloWorld/ror_components")
      end

      def copy_base_files
        base_path = "base/base/"
        base_files = %w[Procfile.dev
                        Procfile.dev-static-assets
                        Procfile.dev-prod-assets
                        .dev-services.yml.example
                        .env.example
                        bin/shakapacker-precompile-hook]

        # react_on_rails_default layout provides empty pack tags so React on Rails can
        # inject generated packs without requiring a hardcoded application.js pack entry.
        base_files << "app/views/layouts/react_on_rails_default.html.erb"

        # HelloWorld controller only when not using RSC (RSC uses HelloServer)
        # Exception: Redux still needs the HelloWorld controller even with RSC
        base_files << "app/controllers/hello_world_controller.rb" unless use_rsc? && !options.redux?
        base_templates = %w[config/initializers/react_on_rails.rb]
        base_files.each { |file| copy_file("#{base_path}#{file}", file) }
        base_templates.each do |file|
          template("#{base_path}/#{file}.tt", file)
        end

        # Make the hook script executable (copy_file guarantees it exists)
        if options[:pretend]
          say_status :pretend, "Skipping chmod on shakapacker-precompile-hook in --pretend mode", :yellow
        else
          File.chmod(0o755, File.join(destination_root, "bin/shakapacker-precompile-hook"))
        end
      end

      def copy_js_bundle_files
        base_path = "base/base/"
        base_files = %w[app/javascript/packs/server-bundle.js]

        # Skip HelloWorld CSS for Redux (uses HelloWorldApp) or RSC (uses HelloServer)
        unless options.redux? || use_rsc?
          base_files << "app/javascript/src/HelloWorld/ror_components/HelloWorld.module.css"
        end

        base_files.each { |file| copy_file("#{base_path}#{file}", file) }
      end

      def copy_webpack_config
        # Cleanup must run before writing new webpack/rspack configs so we only
        # evaluate pre-existing stale entries, never files generated in this run.
        cleanup_stale_webpack_config_dir_for_rspack

        say "Adding #{using_rspack? ? 'Rspack' : 'Webpack'} config"
        base_path = "base/base"
        base_files = %w[babel.config.js
                        config/webpack/clientWebpackConfig.js
                        config/webpack/commonWebpackConfig.js
                        config/webpack/test.js
                        config/webpack/development.js
                        config/webpack/production.js
                        config/webpack/serverWebpackConfig.js
                        config/webpack/ServerClientOrBoth.js]
        config = { message: DOCS_REFERENCE_MESSAGE }
        base_files.each do |file|
          template("#{base_path}/#{file}.tt", destination_config_path(file), config)
        end

        # Handle webpack.config.js separately with smart replacement
        copy_webpack_main_config(base_path, config)
      end

      def copy_packer_config
        base_path = "base/base/"
        config = "config/shakapacker.yml"

        if options.shakapacker_just_installed?
          say "Replacing Shakapacker default config with React on Rails version"
          # Shakapacker's installer just created this file from scratch (no pre-existing config).
          # Safe to overwrite silently with RoR's version-aware template (e.g., private_output_path).
          template("#{base_path}#{config}.tt", config, force: true)
        else
          say "Adding Shakapacker #{ReactOnRails::PackerUtils.shakapacker_version} config"
          # Thor handles the conflict: prompts user interactively, or respects --force/--skip flags.
          template("#{base_path}#{config}.tt", config)
        end

        # Configure bundler-specific settings
        configure_rspack_in_shakapacker if using_rspack?

        # Always ensure precompile_hook is configured (Shakapacker 9.0+ only)
        configure_precompile_hook_in_shakapacker

        # For SSR bundles, configure Shakapacker private_output_path (9.0+ only)
        # This keeps Shakapacker and React on Rails server bundle paths in sync.
        configure_private_output_path_in_shakapacker
      end

      def add_base_gems_to_gemfile
        run "bundle"
      end

      def update_gitignore_for_auto_registration
        gitignore_path = File.join(destination_root, ".gitignore")
        return unless File.exist?(gitignore_path)

        gitignore_content = File.read(gitignore_path)

        additions = []
        additions << "**/generated/**" unless gitignore_content.include?("**/generated/**")
        additions << "ssr-generated" unless gitignore_content.include?("ssr-generated")
        additions << ".env" unless gitignore_content.match?(/^\.env$/)

        return if additions.empty?

        append_to_file ".gitignore" do
          lines = ["\n# React on Rails (generated and local files)"]
          lines.concat(additions)
          "#{lines.join("\n")}\n"
        end
      end

      def append_to_spec_rails_helper
        rspec_helper = preferred_rspec_helper_file
        add_configure_rspec_to_compile_assets(rspec_helper) if rspec_helper

        test_helper = File.join(destination_root, "test/test_helper.rb")
        add_configure_minitest_to_compile_assets(test_helper) if File.exist?(test_helper)
      end

      CONFIGURE_RSPEC_TO_COMPILE_ASSETS = <<~STR
        RSpec.configure do |config|
          # Ensure that if we are running js tests, we are using latest webpack assets
          # This will use the defaults of :js and :server_rendering meta tags
          # Requires config.build_test_command in config/initializers/react_on_rails.rb.
          # This is the default setup for React on Rails generated apps.
          ReactOnRails::TestHelper.configure_rspec_to_compile_assets(config)
        end
      STR

      CONFIGURE_MINITEST_TO_COMPILE_ASSETS = <<~STR
        # Ensure that tests run against fresh webpack assets.
        ActiveSupport::TestCase.setup do
          ReactOnRails::TestHelper.ensure_assets_compiled
        end
      STR

      private

      def preferred_rspec_helper_file
        rails_helper = File.join(destination_root, "spec/rails_helper.rb")
        return rails_helper if File.exist?(rails_helper)

        spec_helper = File.join(destination_root, "spec/spec_helper.rb")
        return spec_helper if File.exist?(spec_helper)

        nil
      end

      def copy_webpack_main_config(base_path, config)
        webpack_config_path = bundler_main_config_path
        template_path = bundler_main_config_template_path(base_path, webpack_config_path)

        if File.exist?(webpack_config_path)
          existing_content = File.read(webpack_config_path)

          # Check if it's the standard Shakapacker config that we can safely replace
          if standard_shakapacker_config?(existing_content, strip_comments: true)
            # Remove the file first to avoid conflict prompt, then recreate it
            remove_file(webpack_config_path, verbose: false)
            # Show what we're doing
            say_status :replace,
                       "#{webpack_config_path} (auto-upgrading from standard Shakapacker to React on Rails config)",
                       :green
            template(template_path, webpack_config_path, config)
          elsif react_on_rails_config?(existing_content)
            say_status :identical, "#{webpack_config_path} (already React on Rails compatible)", :blue
            # Skip - don't need to do anything
          else
            handle_custom_webpack_config(base_path, config, webpack_config_path)
          end
        else
          # File doesn't exist, create it
          template(template_path, webpack_config_path, config)
        end
      end

      def handle_custom_webpack_config(base_path, config, webpack_config_path)
        # Custom config - ask user
        config_file_name = File.basename(webpack_config_path)
        bundler_name = using_rspack? ? "rspack" : "webpack"
        say ""
        say_status :notice, "Your #{config_file_name} appears to be customized.", :yellow
        say "React on Rails needs to replace it with an environment-specific loader."
        say "Your current config will be backed up to #{config_file_name}.backup"

        if yes?("Replace #{config_file_name} with React on Rails version? (Y/n)")
          # Create backup
          backup_path = "#{webpack_config_path}.backup"
          if File.exist?(webpack_config_path)
            FileUtils.cp(webpack_config_path, backup_path)
            say_status :create, "#{backup_path} (backup of your custom config)", :green
          end

          template(bundler_main_config_template_path(base_path, webpack_config_path), webpack_config_path, config)
        else
          say_status :skip, webpack_config_path, :yellow
          say_status :warning,
                     "React on Rails may not work correctly without the environment-specific #{bundler_name} config",
                     :red
        end
      end

      def bundler_main_config_path
        if using_rspack?
          if File.exist?("config/rspack/rspack.config.ts")
            "config/rspack/rspack.config.ts"
          else
            "config/rspack/rspack.config.js"
          end
        elsif File.exist?("config/webpack/webpack.config.ts")
          "config/webpack/webpack.config.ts"
        else
          "config/webpack/webpack.config.js"
        end
      end

      def cleanup_stale_webpack_config_dir_for_rspack
        return unless cleanup_stale_webpack_config_dir?

        webpack_config_relative_dir = "config/webpack"
        all_entries = stale_webpack_config_entries
        unless all_entries
          say_status :warning,
                     "Keeping #{webpack_config_relative_dir}; could not read directory entries " \
                     "(permission denied or path changed)",
                     :yellow
          return
        end
        if all_entries.empty?
          say_status :skip, "#{webpack_config_relative_dir} (empty directory, leaving as-is)", :yellow
          return
        end

        return warn_dotfiles_only_webpack_dir(webpack_config_relative_dir, all_entries) if all_dotfiles?(all_entries)

        # We only clean up known top-level files. Any directory or unknown entry is
        # treated as non-removable so we don't recurse into user-managed content.
        non_removable_entries = non_removable_webpack_entries(all_entries)
        removable_entries = removable_webpack_entries(all_entries)
        if non_removable_entries.empty?
          remove_stale_webpack_dir(webpack_config_relative_dir)
          return
        end

        if all_dotfiles?(non_removable_entries)
          handle_dotfile_only_non_removable_entries(
            webpack_config_relative_dir,
            removable_entries,
            non_removable_entries
          )
          return
        end

        removed_entries = remove_stale_webpack_files(webpack_config_relative_dir, removable_entries)
        warn_non_removable_webpack_entries(webpack_config_relative_dir, non_removable_entries, removed_entries)
      end

      def remove_stale_webpack_dir(webpack_config_relative_dir)
        # Thor's remove_dir uses paths relative to destination_root.
        # TOCTOU: a file created between the removability check and remove_dir
        # would be deleted. Acceptable for this generator cleanup path.
        remove_dir(webpack_config_relative_dir, verbose: false)
        say_status :remove,
                   "#{webpack_config_relative_dir} (stale webpack configs after switching to --rspack)",
                   :green
      end

      def handle_dotfile_only_non_removable_entries(
        webpack_config_relative_dir,
        removable_entries,
        non_removable_entries
      )
        removed_entries = remove_stale_webpack_files(webpack_config_relative_dir, removable_entries)
        warn_dotfiles_in_webpack_dir(webpack_config_relative_dir, non_removable_entries, removed_entries)
      end

      def cleanup_stale_webpack_config_dir?
        using_rspack? && Dir.exist?(stale_webpack_config_dir)
      end

      def all_dotfiles?(entries)
        entries.any? && entries.all? { |entry| entry.start_with?(".") }
      end

      def warn_dotfiles_only_webpack_dir(webpack_config_relative_dir, all_entries)
        say_status :warning,
                   "Keeping #{webpack_config_relative_dir}; only dotfiles found: " \
                   "#{all_entries.join(', ')}",
                   :yellow
      end

      def warn_non_removable_webpack_entries(webpack_config_relative_dir, non_removable_entries, removed_entries = [])
        non_dotfile_entries = non_removable_entries.reject { |entry| entry.start_with?(".") }
        dotfiles = non_removable_entries.select { |entry| entry.start_with?(".") }
        non_removable_directories, non_removable_files = non_dotfile_entries.partition do |entry|
          directory_entry?(entry)
        end

        non_removable_sections = []
        non_removable_sections << "files: #{non_removable_files.join(', ')}" if non_removable_files.any?
        if non_removable_directories.any?
          non_removable_sections << "directories: #{non_removable_directories.join(', ')}"
        end
        non_removable_sections << "dotfiles: #{dotfiles.join(', ')}" if dotfiles.any?

        non_removable_sections_message = non_removable_sections.join("; ")
        removed_entries_message = if removed_entries.any?
                                    " Removed stale managed files: #{removed_entries.join(', ')}."
                                  else
                                    ""
                                  end
        say_status :warning,
                   "Keeping #{webpack_config_relative_dir}; " \
                   "custom/non-removable entries detected: #{non_removable_sections_message}." \
                   "#{removed_entries_message}",
                   :yellow
      end

      def directory_entry?(entry)
        File.directory?(File.join(stale_webpack_config_dir, entry))
      rescue Errno::EACCES, Errno::ELOOP, Errno::ENOENT
        false
      end

      def warn_dotfiles_in_webpack_dir(webpack_config_relative_dir, dotfiles, removed_entries)
        removed_entries_message = if removed_entries.any?
                                    " Removed stale managed files: #{removed_entries.join(', ')}."
                                  else
                                    ""
                                  end
        say_status :warning,
                   "Keeping #{webpack_config_relative_dir}; dotfiles present: #{dotfiles.join(', ')}. " \
                   "Remove them manually if you want the directory cleaned up." \
                   "#{removed_entries_message}",
                   :yellow
      end

      def non_removable_webpack_entries(all_entries)
        all_entries.select do |entry|
          entry.start_with?(".") || !removable_webpack_entry?(entry)
        end
      end

      def removable_webpack_entries(all_entries)
        all_entries.select { |entry| removable_webpack_entry?(entry) }
      end

      def remove_stale_webpack_files(webpack_config_relative_dir, entries)
        entries.each_with_object([]) do |entry, removed_entries|
          relative_path = File.join(webpack_config_relative_dir, entry)
          full_path = File.join(destination_root, relative_path)
          remove_file(relative_path, verbose: false)
          removed_entries << entry unless File.exist?(full_path)
        rescue Errno::EACCES, Errno::ELOOP, Errno::ENOENT, Errno::ENOTDIR
          # If we cannot stat after removal attempt, conservatively report as not removed.
          nil
        end
      end

      def removable_webpack_entry?(entry)
        return false unless REMOVABLE_WEBPACK_FILES.include?(entry)

        full_path = File.join(stale_webpack_config_dir, entry)
        return false if File.symlink?(full_path)
        return false unless File.file?(full_path)

        content = safe_read_cleanup_file(full_path)
        return false unless content

        return removable_webpack_main_config?(content) if entry == "webpack.config.js"

        removable_managed_webpack_entry?(entry, content)
      rescue Errno::EACCES, Errno::ELOOP, Errno::ENOENT, Errno::ENOTDIR
        false
      end

      def removable_webpack_main_config?(content)
        webpack_template = rendered_template_for_cleanup("base/base/config/webpack/webpack.config.js.tt")
        return standard_shakapacker_config?(content) if webpack_template.equal?(TEMPLATE_RENDER_FAILED)

        # Cleanup is deliberately comment-sensitive (unlike copy_webpack_main_config)
        # so comment-only edits keep the file as a potential customization.
        standard_shakapacker_config?(content) || content_matches_template?(content, webpack_template)
      end

      def removable_managed_webpack_entry?(entry, content)
        template_path = MANAGED_WEBPACK_FILE_TEMPLATES[entry]
        return false unless template_path

        rendered_template = rendered_template_for_cleanup(template_path)
        return false if rendered_template.equal?(TEMPLATE_RENDER_FAILED)

        content_matches_template?(content, rendered_template)
      end

      def rendered_template_for_cleanup(template_path)
        @rendered_template_cache ||= {}
        @rendered_template_cache[template_path] ||= begin
          # Cleanup comparisons only need the injected documentation comment.
          template_doc_config = { message: DOCS_REFERENCE_MESSAGE }
          template_content = File.read(File.join(self.class.source_root, template_path))
          # Render against current generator options. Any mismatch is treated as non-removable,
          # which is intentional because cleanup should be conservative.
          # Note: files originally generated with --pro or --rsc will not match when the
          # current run omits those options; in that case, we preserve the directory.
          # Templates rely on config[:message] plus a small helper subset exposed by
          # TemplateRenderContext (add_documentation_reference, use_pro?, use_rsc?,
          # shakapacker_version_9_or_higher?). Missing method delegates raise
          # NoMethodError and are caught below, treating the file as non-removable.
          # Missing config hash keys return nil silently, so any new config key
          # required by templates must be added to template_doc_config above.
          # Use TemplateRenderContext#erb_binding to avoid leaking method-local
          # variables from rendered_template_for_cleanup into the ERB scope.
          template_render_context = TemplateRenderContext.new(self, template_doc_config)
          ERB.new(template_content, trim_mode: "-").result(template_render_context.erb_binding)
        rescue StandardError => e
          say_status :warning,
                     "Could not render template #{template_path} for cleanup check (#{e.class}: #{e.message}); " \
                     "treating as non-removable",
                     :yellow
          # Rendering failures should never abort installation. Returning a sentinel
          # guarantees a non-match so the file is treated as non-removable.
          # We cache the sentinel intentionally (same options within one generator run)
          # so repeated checks stay consistent and avoid noisy duplicate warnings.
          TEMPLATE_RENDER_FAILED
        end
      end

      def stale_webpack_config_dir
        File.join(destination_root, "config/webpack")
      end

      def stale_webpack_config_entries
        Dir.children(stale_webpack_config_dir).sort
      rescue Errno::EACCES, Errno::ENOENT, Errno::ENOTDIR
        # TOCTOU: directory may disappear between exist? check and read
        nil
      end

      def safe_read_cleanup_file(path)
        File.read(path)
      rescue Errno::EACCES, Errno::ELOOP, Errno::ENOENT, Errno::EISDIR, Errno::ENOTDIR
        nil
      end

      def standard_shakapacker_config?(content, strip_comments: false)
        # Keep strip_comments false by default so comment-only edits are treated as
        # potential customizations during cleanup. Callers can pass true when they
        # need historical comment-insensitive replacement matching.
        # Get the expected default config based on Shakapacker version
        expected_configs = shakapacker_default_configs

        # Check if the content matches any of the known default configurations
        expected_configs.any? { |config| content_matches_template?(content, config, strip_comments: strip_comments) }
      end

      def content_matches_template?(content, template, strip_comments: false)
        # Normalize whitespace and compare
        normalize_config_content(content, strip_comments: strip_comments) ==
          normalize_config_content(template, strip_comments: strip_comments)
      end

      def normalize_config_content(content, strip_comments: false)
        normalized_content = content
        if strip_comments
          # Replacement detection historically removed inline // comments too.
          # Note: this also strips `//` in string literals (for example URLs),
          # which can yield false-negatives and prompt for replacement.
          normalized_content = normalized_content.gsub(%r{//.*$}, "")
                                                 .gsub(%r{/\*.*?\*/}m, "")
        end

        # Normalize whitespace while preserving comments by default so added comments
        # count as potential customizations and keep cleanup conservative.
        normalized_content.gsub(/\s+/, " ")
                          .tr('"', "'") # Normalize quote style for import/require statements
                          .strip
      end

      def bundler_main_config_template_path(base_path, config_path)
        template_ext = config_path.end_with?(".ts") ? "ts.tt" : "js.tt"
        template_base = if config_path.include?("/rspack/") || File.basename(config_path).start_with?("rspack.config")
                          "rspack.config"
                        else
                          "webpack.config"
                        end
        "#{base_path}/config/webpack/#{template_base}.#{template_ext}"
      end

      def shakapacker_default_configs
        shakapacker_cjs_default_configs + shakapacker_esm_default_configs
      end

      def shakapacker_cjs_default_configs
        configs = []

        # Shakapacker v7+ (generateWebpackConfig function)
        configs << <<~CONFIG
          // See the shakacode/shakapacker README and docs directory for advice on customizing your webpackConfig.
          const { generateWebpackConfig } = require('shakapacker')

          const webpackConfig = generateWebpackConfig()

          module.exports = webpackConfig
        CONFIG

        # Shakapacker v6 (webpackConfig object)
        configs << <<~CONFIG
          const { webpackConfig } = require('shakapacker')

          // See the shakacode/shakapacker README and docs directory for advice on customizing your webpackConfig.

          module.exports = webpackConfig
        CONFIG

        # Also check without comments for variations
        configs << <<~CONFIG
          const { generateWebpackConfig } = require('shakapacker')
          const webpackConfig = generateWebpackConfig()
          module.exports = webpackConfig
        CONFIG

        configs << <<~CONFIG
          const { webpackConfig } = require('shakapacker')
          module.exports = webpackConfig
        CONFIG

        # Shakapacker v9+ rspack configs (generateRspackConfig function)
        configs << <<~CONFIG
          // See the shakacode/shakapacker README and docs directory for advice on customizing your rspackConfig.
          const { generateRspackConfig } = require('shakapacker/rspack')

          const rspackConfig = generateRspackConfig()

          module.exports = rspackConfig
        CONFIG

        configs << <<~CONFIG
          const { generateRspackConfig } = require('shakapacker/rspack')
          const rspackConfig = generateRspackConfig()
          module.exports = rspackConfig
        CONFIG

        configs
      end

      def shakapacker_esm_default_configs
        configs = []

        # Shakapacker v9.4+ TypeScript webpack configs (ESM syntax)
        configs << <<~CONFIG
          import { generateWebpackConfig } from 'shakapacker'
          import type { Configuration } from 'webpack'
          const webpackConfig: Configuration = generateWebpackConfig()
          export default webpackConfig
        CONFIG

        configs << <<~CONFIG
          import { generateWebpackConfig } from 'shakapacker'
          const webpackConfig = generateWebpackConfig()
          export default webpackConfig
        CONFIG

        # Shakapacker v9.4+ TypeScript rspack configs (ESM syntax)
        configs << <<~CONFIG
          import { generateRspackConfig } from 'shakapacker/rspack'
          import type { RspackOptions } from '@rspack/core'
          const rspackConfig: RspackOptions = generateRspackConfig()
          export default rspackConfig
        CONFIG

        configs << <<~CONFIG
          import { generateRspackConfig } from 'shakapacker/rspack'
          const rspackConfig = generateRspackConfig()
          export default rspackConfig
        CONFIG

        configs
      end

      def react_on_rails_config?(content)
        # Check if it already has React on Rails environment-specific loading
        content.include?("envSpecificConfig") || content.include?("env.nodeEnv")
      end

      # From https://github.com/rails/rails/blob/4c940b2dbfb457f67c6250b720f63501d74a45fd/railties/lib/rails/generators/rails/app/app_generator.rb
      def app_name
        @app_name ||= (defined_app_const_base? ? defined_app_name : File.basename(destination_root))
                      .tr("\\", "").tr(". ", "_")
      end

      def defined_app_name
        defined_app_const_base.underscore
      end

      def defined_app_const_base
        Rails.respond_to?(:application) && defined?(Rails::Application) &&
          Rails.application.is_a?(Rails::Application) && Rails.application.class.name.sub(/::Application$/, "")
      end

      alias defined_app_const_base? defined_app_const_base

      def app_const_base
        @app_const_base ||= defined_app_const_base || app_name.gsub(/\W/, "_").squeeze("_").camelize
      end

      def app_const
        @app_const ||= "#{app_const_base}::Application"
      end

      def add_configure_rspec_to_compile_assets(helper_file)
        content = File.read(helper_file)
        return if content.match?(/^\s*[^#\s][^#]*ReactOnRails::TestHelper\.configure_rspec_to_compile_assets/)

        updated_content = content.sub("RSpec.configure do |config|", CONFIGURE_RSPEC_TO_COMPILE_ASSETS)
        return if updated_content == content

        File.write(helper_file, updated_content)
      end

      def add_configure_minitest_to_compile_assets(helper_file)
        content = File.read(helper_file)
        return if content.match?(/^\s*[^#\s][^#]*ReactOnRails::TestHelper\.ensure_assets_compiled/)

        append_to_file(helper_file, "\n\n#{CONFIGURE_MINITEST_TO_COMPILE_ASSETS}\n")
      end

      def configure_rspack_in_shakapacker
        shakapacker_config_path = "config/shakapacker.yml"
        return unless File.exist?(shakapacker_config_path)

        say "🔧 Configuring Shakapacker for Rspack...", :yellow

        # Use regex replacement to preserve file structure (comments, anchors, aliases)
        # This replaces ALL occurrences of assets_bundler, not just in default section
        # Using gsub_file (Thor method) for consistency with Rails generator patterns
        gsub_file(
          shakapacker_config_path,
          /^(\s*assets_bundler:\s*)["']?webpack["']?(\s*(?:#.*)?)$/,
          '\1rspack\2'
        )

        # Update javascript_transpiler to swc (rspack works best with SWC)
        gsub_file(
          shakapacker_config_path,
          /^(\s*javascript_transpiler:\s*)["']?babel["']?(\s*(?:#.*)?)$/,
          '\1swc\2'
        )

        say "✅ Updated shakapacker.yml for Rspack", :green
      end

      def configure_precompile_hook_in_shakapacker
        # precompile_hook is only supported in Shakapacker 9.0+
        return unless ReactOnRails::PackerUtils.shakapacker_version_requirement_met?("9.0.0")

        shakapacker_config_path = "config/shakapacker.yml"
        return unless File.exist?(shakapacker_config_path)

        content = File.read(shakapacker_config_path)

        # Already has an active (non-commented) precompile_hook configured? Don't overwrite.
        return if content.match?(/^\s+precompile_hook:\s*['"][^'"]+['"]/)

        # Replace the commented placeholder with the actual value
        # Shakapacker 9.x default config has: # precompile_hook: ~
        gsub_file shakapacker_config_path,
                  /^(\s*)#\s*precompile_hook:\s*~\s*$/,
                  "\\1precompile_hook: 'bin/shakapacker-precompile-hook'"

        say "✅ Configured precompile_hook in shakapacker.yml", :green
      end

      def configure_private_output_path_in_shakapacker
        # private_output_path is only supported in Shakapacker 9.0+
        return unless ReactOnRails::PackerUtils.shakapacker_version_requirement_met?("9.0.0")

        shakapacker_config_path = "config/shakapacker.yml"
        return unless File.exist?(shakapacker_config_path)

        content = File.read(shakapacker_config_path)

        # A non-empty active value means the app already made an explicit choice.
        return if content.match?(/^\s+private_output_path:\s*\S+/)

        # Normalize an empty active key before falling back to insertion.
        gsub_file(
          shakapacker_config_path,
          /^(\s*)private_output_path:\s*$/,
          "\\1private_output_path: ssr-generated"
        )

        # First try: uncomment an existing private_output_path placeholder line.
        gsub_file(
          shakapacker_config_path,
          /^(\s*)#\s*private_output_path:\s*.*$/,
          "\\1private_output_path: ssr-generated"
        )

        # Fallback: insert directly after public_output_path in the same section.
        unless File.read(shakapacker_config_path).match?(/^\s+private_output_path:\s*ssr-generated/)
          gsub_file(
            shakapacker_config_path,
            /^(\s*)(public_output_path:\s*.*\n)/,
            "\\1\\2\\1private_output_path: ssr-generated\n"
          )
        end

        return unless File.read(shakapacker_config_path).match?(/^\s+private_output_path:\s*ssr-generated/)

        say "✅ Configured private_output_path in shakapacker.yml", :green
      end
    end
  end
end
