const fs = require('fs');
const path = require('path');
const { config } = require('shakapacker');

// Resolves the RSC client-reference manifest for the client and server webpack builds.
//
// This intentionally mirrors, branch for branch, the resolution contract the react_on_rails RSC
// setup generator emits inline (`rsc_client_references_js` in
// react_on_rails/lib/generators/react_on_rails/rsc_setup/client_references.rb). The shared contract
// that must stay in sync on both sides:
//   - override env var:   RSC_MANIFEST_CLIENT_REFERENCES_JSON (path.resolve'd; must exist, else throw
//     "... is set but the file does not exist", then read)
//   - default manifest:   ssr-generated/rsc-client-references.json (resolved against the Rails root)
//   - manifest shape:     { refs: [...] }, else throw "... to contain a refs array"
//   - parse errors:       malformed JSON re-thrown as "Failed to parse RSC client references manifest ..."
//   - fallback ordering:  configured JSON -> default JSON -> (discovery/bundle-only build -> broad
//     fallback) -> (registration entry present -> throw the precompile-hook hint) -> broad fallback
//   - staleness warning:  default manifest older than the registration entry -> console.warn (non-fatal)
//   - precompile hint:    "Run bin/shakapacker-precompile-hook before bin/shakapacker."
// Both sides are pinned by contract tests so drift on either side fails CI: this resolver by the
// dummy-root tests/rsc-manifest-client-references.test.js (run by the Pro `package-js-tests` CI
// job), and the generator by react_on_rails/spec/react_on_rails/generators/rsc_generator_spec.rb.
//
// The manifest is a point-in-time snapshot regenerated by bin/shakapacker-precompile-hook, not on
// every webpack rebuild: a `--watch` build reads it once at startup, so a new 'use client' file
// added mid-session is not picked up until the watch restarts. See warnIfManifestStale below.
//
// Only the fallback `directory` (`./client/app`) is intentionally app-specific. It is deliberately
// scoped to the app source directory to keep the broad scan from traversing into node_modules/
// (which, with pnpm workspace symlinks, exposes .tsx source files that lack a configured loader).
// The `include` extension set is kept byte-identical to the generator template and is pinned in
// lockstep by the contract test.
const DEFAULT_CLIENT_REFERENCES = [
  { directory: './client/app', recursive: true, include: /\.(js|mjs|cjs|ts|mts|cts|jsx|tsx)$/ },
];

// cwd-relative (the Rails root at webpack build time), matching the generated template's
// `resolve('ssr-generated/rsc-client-references.json')` rather than coupling to this file's location.
const DEFAULT_REFERENCES_JSON = path.resolve('ssr-generated/rsc-client-references.json');
const SERVER_COMPONENT_REGISTRATION_ENTRY = path.resolve(
  config.source_path,
  config.source_entry_path,
  '../generated/server-component-registration-entry.js',
);

function readManifestReferences(refsJson) {
  let payload;
  try {
    payload = JSON.parse(fs.readFileSync(refsJson, 'utf8'));
  } catch (err) {
    throw new Error(`Failed to parse RSC client references manifest ${refsJson}: ${err.message}`);
  }
  if (!Array.isArray(payload.refs)) {
    throw new Error(`Expected ${refsJson} to contain a refs array`);
  }

  return payload.refs;
}

// Warn (do not fail) when the discovered manifest predates the registration entry: the set of
// server components changed but the discovery build was not re-run, so the refs may be stale. This
// is best-effort — it cannot detect a new 'use client' file reached by an unchanged server
// component (that is the `--watch` snapshot limitation documented above).
function warnIfManifestStale() {
  if (
    fs.existsSync(SERVER_COMPONENT_REGISTRATION_ENTRY) &&
    fs.statSync(SERVER_COMPONENT_REGISTRATION_ENTRY).mtimeMs > fs.statSync(DEFAULT_REFERENCES_JSON).mtimeMs
  ) {
    console.warn(
      `[react_on_rails] ${DEFAULT_REFERENCES_JSON} is older than the server component ` +
        'registration entry; RSC client references may be stale. ' +
        'Re-run bin/shakapacker-precompile-hook.',
    );
  }
}

function rscManifestClientReferences() {
  const configuredRefsJson = process.env.RSC_MANIFEST_CLIENT_REFERENCES_JSON;
  if (configuredRefsJson) {
    const resolvedRefsJson = path.resolve(configuredRefsJson);
    if (!fs.existsSync(resolvedRefsJson)) {
      throw new Error(
        `RSC_MANIFEST_CLIENT_REFERENCES_JSON is set but the file does not exist: ${resolvedRefsJson}`,
      );
    }
    return readManifestReferences(resolvedRefsJson);
  }

  if (fs.existsSync(DEFAULT_REFERENCES_JSON)) {
    warnIfManifestStale();
    return readManifestReferences(DEFAULT_REFERENCES_JSON);
  }

  if (process.env.RSC_REFERENCE_DISCOVERY_BUILD === 'true' || process.env.RSC_BUNDLE_ONLY === 'true') {
    return DEFAULT_CLIENT_REFERENCES;
  }

  if (fs.existsSync(SERVER_COMPONENT_REGISTRATION_ENTRY)) {
    throw new Error(
      `Missing ${DEFAULT_REFERENCES_JSON}. Run bin/shakapacker-precompile-hook before bin/shakapacker.`,
    );
  }

  return DEFAULT_CLIENT_REFERENCES;
}

module.exports = rscManifestClientReferences;
