module ReactOnRails
  module RenderingStrategy
    class ExecJsStrategy
      include ReactOnRails::RenderingStrategy

      def execute: (RenderRequest render_request) -> untyped
      def reset: () -> void
      def reset_if_bundle_changed: () -> void
    end
  end
end
