module ReactOnRails
  class JsCodeBuilder
    def build: (RenderRequest render_request) -> String
    def build_sections: (RenderRequest render_request) -> Array[String?]
    def rails_context_section: (RenderRequest render_request) -> String
    def store_initialization_section: (RenderRequest render_request) -> String
    def props_section: (RenderRequest render_request) -> String
    def render_call_section: (RenderRequest render_request) -> String
    def wrap_in_iife: (String body, RenderRequest render_request) -> String
  end
end
