module ReactOnRails
  module PackerUtils
    def self.supports_autobundling?: () -> bool
    def self.supports_async_loading?: () -> bool
    def self.nested_entries?: () -> bool
    def self.packer_public_output_path: () -> String
    def self.precompile?: () -> bool
    def self.shakapacker_precompile_hook_configured?: () -> bool
    def self.shakapacker_precompile_hook_value: () -> String?
    def self.raise_shakapacker_version_incompatible_for_autobundling: () -> void
    def self.raise_nested_entries_disabled: () -> void
  end
end
