module ReactOnRails
  class RenderRequest
    attr_reader component_name: String
    attr_reader props: Hash[untyped, untyped] | String
    attr_reader rails_context: Hash[untyped, untyped]
    attr_reader store_initializations: String
    attr_reader render_options: untyped

    def initialize: (
      component_name: String,
      props: Hash[untyped, untyped] | String,
      rails_context: Hash[untyped, untyped],
      store_initializations: String,
      render_options: untyped
    ) -> void

    def to_js: () -> String
    def props_string: () -> String
    def rails_context_json: () -> String
    def dom_id: () -> String
    def streaming?: () -> bool
    def rsc_payload_streaming?: () -> bool

    private

    def validate_server_bundle_configured!: () -> void
  end
end
