# frozen_string_literal: true

source "https://rubygems.org"

eval_gemfile File.expand_path("../../react_on_rails.gemspec", __dir__)

gem "react_on_rails", path: "../.."

gem "webpacker"

gem "bootsnap", ">= 1.1.0", require: false
gem "rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3"
# Use SCSS for stylesheets
gem "sass-rails"
# Use Uglifier as compressor for JavaScript assets
gem "uglifier"
# Use CoffeeScript for .coffee assets and views
gem "coffee-rails"

# Use jquery as the JavaScript library
gem "jquery-rails"

gem "puma"

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem "turbolinks" if ENV["DISABLE_TURBOLINKS"].nil? || ENV["DISABLE_TURBOLINKS"].strip.empty?

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder"
# bundle exec rake doc:rails generates the API under doc/api.
gem "sdoc", group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem "awesome_print"
gem "mini_racer"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "listen"
  gem "pry"
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  gem "pry-rescue"
  gem "pry-stack_explorer"
  gem "rubocop", require: false
  gem "ruby-lint", require: false
  gem "scss_lint", require: false

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
end

group :test do
  gem "capybara"
  gem "capybara-screenshot"
  gem "coveralls", require: false
  # install trouble with updated
  # gem "capybara-webkit"
  gem "chromedriver-helper"
  gem "equivalent-xml", github: "mbklein/equivalent-xml"
  gem "generator_spec"
  gem "launchy"
  gem "rspec-rails"
  gem "rspec-retry"
  gem "selenium-webdriver"
end
