# frozen_string_literal: true

require_relative "spec_helper"
require "tmpdir"

module ReactOnRails
  RSpec.describe TypeScriptResponseTypes do
    before { described_class.reset! }

    after { described_class.reset! }

    it "emits named types, response types, and the response lookup map" do
      described_class.define_type(
        "Project",
        fields: {
          id: :number,
          name: :string,
          status: :string,
          owner: {
            fields: {
              id: :number,
              display_name: { type: :string, optional: true, nullable: true }
            }
          }
        }
      )
      described_class.define_response(
        "projects.index",
        type_name: "ProjectsIndexResponse",
        fields: {
          projects: { array: "Project" },
          meta: {
            fields: {
              page: :number,
              "per-page": :number
            }
          }
        }
      )

      expect(described_class.to_d_ts).to eq(<<~TS)
        // Generated by react_on_rails:generate_response_types. Do not edit by hand.

        export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

        export interface Project {
          id: number;
          name: string;
          status: string;
          owner: {
            id: number;
            display_name?: string | null;
          };
        }

        export interface ProjectsIndexResponse {
          projects: Project[];
          meta: {
            page: number;
            "per-page": number;
          };
        }

        export interface RailsResponseTypes {
          "projects.index": ProjectsIndexResponse;
        }

        export type RailsResponseTypeName = keyof RailsResponseTypes;
        export type RailsResponseType<TName extends RailsResponseTypeName> = RailsResponseTypes[TName];
      TS
    end

    it "writes the generated declaration file" do
      described_class.define_response("health.show", type_name: "HealthResponse", fields: { ok: :boolean })

      Dir.mktmpdir do |dir|
        output_path = File.join(dir, "generated", "rails_response_types.d.ts")

        expect(described_class.generate(output_path:)).to eq(output_path)
        expect(File.read(output_path)).to include("export interface HealthResponse")
      end
    end

    it "treats symbols as scalar aliases and strings as custom type references" do
      described_class.define_type("ApiDate", fields: { iso8601: :string })
      described_class.define_response(
        "events.show",
        type_name: "EventsShowResponse",
        fields: {
          starts_at: "ApiDate",
          created_on: :date
        }
      )

      expect(described_class.to_d_ts).to include("starts_at: ApiDate;")
      expect(described_class.to_d_ts).to include("created_on: string;")
    end

    it "does not treat shorthand object child fields as parent modifiers" do
      described_class.define_response(
        "metadata.show",
        type_name: "MetadataShowResponse",
        fields: {
          metadata: {
            optional: :boolean,
            nullable: :boolean,
            name: :string
          }
        }
      )

      declaration = described_class.to_d_ts

      expected_metadata_type = [
        "  metadata: {",
        "    optional: boolean;",
        "    nullable: boolean;",
        "    name: string;",
        "  };"
      ].join("\n")

      expect(declaration).to include(expected_metadata_type)
      expect(declaration).not_to include("metadata?:")
    end

    it "rejects duplicate response keys" do
      described_class.define_response("projects.index", type_name: "ProjectsIndexResponse", fields: {})

      expect do
        described_class.define_response("projects.index", type_name: "OtherProjectsResponse", fields: {})
      end.to raise_error(ReactOnRails::Error, /Duplicate response type key: projects\.index/)
    end

    it "rejects invalid TypeScript type names" do
      expect do
        described_class.define_type("project-response", fields: {})
      end.to raise_error(ReactOnRails::Error, /valid identifier/)
    end

    it "rejects names that would collide with TypeScript or generated declarations" do
      expect do
        described_class.define_type("string", fields: {})
      end.to raise_error(ReactOnRails::Error, /valid identifier/)

      expect do
        described_class.define_type("default", fields: {})
      end.to raise_error(ReactOnRails::Error, /valid identifier/)

      expect do
        described_class.define_type("JsonValue", fields: {})
      end.to raise_error(ReactOnRails::Error, /valid identifier/)
    end
  end
end
