#!/usr/bin/env ruby
# frozen_string_literal: true

def gsub_file_content(path, old_content, new_content)
  path = File.expand_path(path, __dir__)
  content = File.binread(path)
  content.gsub!(old_content, new_content)
  File.binwrite(path, content)
end

old_config = File.expand_path("../spec/dummy/config/shakapacker.yml", __dir__)
new_config = File.expand_path("../spec/dummy/config/webpacker.yml", __dir__)

File.rename(old_config, new_config)

gsub_file_content("../Gemfile.development_dependencies", /gem "shakapacker", "[^"]*"/, 'gem "shakapacker", "6.6.0"')

# The below packages don't work on the oldest supported Node version and aren't needed there anyway
gsub_file_content("../package.json", /"eslint": "[^"]*",/, "")
gsub_file_content("../package.json", /"globals": "[^"]*",/, "")
gsub_file_content("../package.json", /"knip": "[^"]*",/, "")
gsub_file_content("../package.json", /"typescript-eslint": "[^"]*",/, "")
gsub_file_content("../package.json", %r{"@arethetypeswrong/cli": "[^"]*",}, "")
gsub_file_content("../package.json", %r{"@testing-library/dom": "[^"]*",}, "")
gsub_file_content("../package.json", %r{"@testing-library/react": "[^"]*",}, "")
gsub_file_content("../package.json", /"knip": "[^"]*",/, "")
gsub_file_content("../package.json", /"publint": "[^"]*",/, "")

gsub_file_content("../spec/dummy/package.json", /"shakapacker": "[^"]*",/, '"shakapacker": "6.6.0",')

gsub_file_content("../spec/dummy/config/webpack/commonWebpackConfig.js", /generateWebpackConfig(\(\))?/,
                  "webpackConfig")

gsub_file_content("../spec/dummy/config/webpack/webpack.config.js", /generateWebpackConfig(\(\))?/, "webpackConfig")
