// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");

function HelloWorldReScript(Props) {
  var helloWorldData = Props.helloWorldData;
  var match = React.useState(function () {
        return helloWorldData.name;
      });
  var setNameState = match[1];
  var nameState = match[0];
  return React.createElement("div", undefined, React.createElement("h3", undefined, "Hello, " + nameState + " !"), React.createElement("hr", undefined), React.createElement("form", undefined, React.createElement("label", {
                      htmlFor: "name"
                    }, "Say hello to: ", React.createElement("input", {
                          id: "name",
                          type: "text",
                          value: nameState,
                          onChange: (function (e) {
                              return Curry._1(setNameState, e.currentTarget.value);
                            })
                        }))));
}

var make = HelloWorldReScript;

exports.make = make;
/* react Not a pure module */
