// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function make(title) {
  return React.createElement("div", {
              className: "app"
            }, React.createElement("div", {
                  className: "title"
                }, title), React.createElement("div", {
                  className: "items"
                }, "Hello World"));
}

exports.make = make;
/* react Not a pure module */
