#!/bin/bash
# Update the example rails node packages

npm run clean
npm run build
# root_path="../../$(dirname "${BASH_SOURCE}")"x
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
root_path=${DIR}/../..
# echo $root_path
(cd $root_path && npm link)
for type in $( ls ${root_path}/examples ); do
  d=examples/${type}/client
  (cd $d && npm link react-on-rails)
done
