# Inherits from root config
inherit_from: ../.rubocop.yml

# Merge Exclude arrays with parent instead of replacing them
inherit_mode:
  merge:
    - Exclude

AllCops:
  SuggestExtensions: false

  Exclude:
    - 'spec/dummy/bin/*'

Naming/FileName:
  Exclude:
    - '**/Gemfile*'
    - '**/Rakefile'
    - '**/Steepfile'

Lint/AssignmentInCondition:
  Exclude:
    - 'spec/dummy/bin/spring'

Lint/SuppressedException:
  Exclude:
    - 'spec/dummy/bin/rails'
    - 'spec/dummy/bin/rake'

Metrics/AbcSize:
  Exclude:
    - 'lib/generators/react_on_rails/install_generator.rb'  # Generator setup methods require comprehensive error handling

Metrics/ClassLength:
  Exclude:
    - 'lib/generators/react_on_rails/base_generator.rb'  # Generator complexity justified
    - 'lib/react_on_rails/dev/server_manager.rb'  # Dev tool with comprehensive help system

Metrics/MethodLength:
  Exclude:
    - 'lib/generators/react_on_rails/install_generator.rb'  # Generator setup methods require comprehensive error handling

Metrics/ModuleLength:
  Exclude:
    - 'spec/react_on_rails/engine_spec.rb'  # Comprehensive engine tests require many examples

Naming/RescuedExceptionsVariableName:
  Enabled: false

RSpec/AnyInstance:
  Exclude:
    - 'spec/react_on_rails/git_utils_spec.rb'
    - 'spec/react_on_rails/locales_to_js_spec.rb'
    - 'spec/react_on_rails/binstubs/dev_spec.rb'
    - 'spec/react_on_rails/binstubs/dev_static_spec.rb'
    - 'spec/react_on_rails/dev/**/*_spec.rb'  # Dev module tests require system mocking

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/react_on_rails/generators/dev_tests_generator_spec.rb'
    - 'spec/react_on_rails/generators/install_generator_spec.rb'
    - 'spec/react_on_rails/generators/pro_generator_spec.rb'
    - 'spec/react_on_rails/generators/rsc_generator_spec.rb'
    - 'spec/react_on_rails/binstubs/dev_spec.rb'
    - 'spec/react_on_rails/binstubs/dev_static_spec.rb'
    - 'spec/react_on_rails/dev/**/*_spec.rb'  # Dev module tests require global setup

RSpec/MultipleDescribes:
  Exclude:
    - 'spec/dummy/spec/system/integration_spec.rb'

Style/GlobalVars:
  Exclude:
    - 'spec/dummy/config/environments/development.rb'

RSpec/NoExpectationExample:
  AllowedPatterns:
    - ^expect_
    - ^assert_

RSpec/InstanceVariable:
  Exclude:
    - 'spec/react_on_rails/dev/**/*_spec.rb'  # Dev module tests require global variable management

RSpec/StubbedMock:
  Exclude:
    - 'spec/react_on_rails/dev/**/*_spec.rb'  # Dev module tests use mixed stub/mock patterns
