# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem"s dependencies in react_on_rails.gemspec
gemspec

Dir.chdir(__dir__) { eval_gemfile "./Gemfile.development_dependencies" }
