import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Intentionally excluded from sidebar (legacy stubs that redirect to archive):
// - building-features/hmr-and-hot-reloading-with-the-webpack-dev-server
// - building-features/rails-webpacker-react-integration-options
// - deployment/troubleshooting-when-using-webpacker
// - misc/asset-pipeline

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'README',
    {
      type: 'category',
      label: 'Choose a Path',
      collapsed: false,
      items: [
        { type: 'ref', id: 'getting-started/create-react-on-rails-app' },
        { type: 'ref', id: 'getting-started/installation-into-an-existing-rails-app' },
        { type: 'ref', id: 'getting-started/oss-vs-pro' },
        { type: 'ref', id: 'pro/upgrading-to-pro' },
        { type: 'ref', id: 'migrating/migrating-from-react-rails' },
      ],
    },
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'generated-index', title: 'Getting Started' },
      collapsed: false,
      items: [
        'getting-started/quick-start',
        'getting-started/create-react-on-rails-app',
        'getting-started/tutorial',
        'getting-started/installation-into-an-existing-rails-app',
        'getting-started/project-structure',
        'getting-started/using-react-on-rails',
        'getting-started/oss-vs-pro',
        'getting-started/pro-quick-start',
        'getting-started/comparison-with-alternatives',
        'getting-started/comparing-react-on-rails-to-alternatives',
        'getting-started/nextjs-with-separate-rails-backend',
        'getting-started/common-issues',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      link: { type: 'generated-index', title: 'Core Concepts' },
      items: [
        'core-concepts/how-react-on-rails-works',
        'core-concepts/client-vs-server-rendering',
        'core-concepts/react-server-rendering',
        'core-concepts/render-functions-and-railscontext',
        'core-concepts/render-functions',
        'core-concepts/auto-bundling-file-system-based-automated-bundle-generation',
        'core-concepts/webpack-configuration',
        'core-concepts/execjs-limitations',
        'core-concepts/performance-benchmarks',
        { type: 'ref', id: 'pro/react-on-rails-pro' },
      ],
    },
    {
      type: 'category',
      label: 'Building Features',
      link: { type: 'generated-index', title: 'Building Features' },
      items: [
        'building-features/react-and-redux',
        'building-features/react-router',
        'building-features/tanstack-router',
        'building-features/code-splitting',
        'building-features/i18n',
        'building-features/images',
        'building-features/react-helmet',
        'building-features/react-19-native-metadata',
        'building-features/streaming-server-rendering',
        'building-features/how-to-conditionally-server-render-based-on-device-type',
        'building-features/how-to-use-different-files-for-client-and-server-rendering',
        'building-features/caching',
        'building-features/bundle-caching',
        'building-features/process-managers',
        'building-features/dev-server-and-testing',
        'building-features/testing-configuration',
        'building-features/extensible-precompile-pattern',
        'building-features/rails-engine-integration',
        'building-features/debugging',
        'building-features/turbolinks',
        {
          type: 'category',
          label: 'Node Renderer (Pro)',
          items: [
            'building-features/node-renderer/basics',
            'building-features/node-renderer/js-configuration',
            'building-features/node-renderer/container-deployment',
            'building-features/node-renderer/debugging',
            'building-features/node-renderer/error-reporting-and-tracing',
            'building-features/node-renderer/heroku',
            'building-features/node-renderer/troubleshooting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'configuration/README',
        'configuration/configuration-pro',
        'configuration/configuration-deprecated',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api-reference/view-helpers-api',
        'api-reference/javascript-api',
        'api-reference/redux-store-api',
        'api-reference/ruby-api-pro',
        'api-reference/generator-details',
        'api-reference/rails-view-rendering-from-inline-javascript',
      ],
    },
    {
      type: 'category',
      label: 'React Server Components',
      items: [
        'pro/react-server-components/index',
        'pro/react-server-components/purpose-and-benefits',
        'pro/react-server-components/how-react-server-components-work',
        'pro/react-server-components/rendering-flow',
        'pro/react-server-components/tutorial',
        'pro/react-server-components/server-side-rendering',
        'pro/react-server-components/add-streaming-and-interactivity',
        'pro/react-server-components/create-without-ssr',
        'pro/react-server-components/inside-client-components',
        'pro/react-server-components/selective-hydration-in-streamed-components',
        'pro/react-server-components/flight-protocol-syntax',
        'pro/react-server-components/upgrading-existing-pro-app',
        'pro/react-server-components/glossary',
        {
          type: 'category',
          label: 'Migrating to RSC',
          items: [
            'migrating/migrating-to-rsc',
            'migrating/rsc-preparing-app',
            'migrating/rsc-component-patterns',
            'migrating/rsc-data-fetching',
            'migrating/rsc-context-and-state',
            'migrating/rsc-third-party-libs',
            'migrating/rsc-flight-payload',
            'migrating/rsc-troubleshooting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/README',
        'deployment/heroku-deployment',
        'deployment/elastic-beanstalk',
        'deployment/capistrano-deployment',
        'deployment/server-rendering-tips',
        'deployment/troubleshooting',
        'deployment/troubleshooting-build-errors',
        'deployment/troubleshooting-when-using-shakapacker',
      ],
    },
    {
      type: 'category',
      label: 'Upgrading',
      items: [
        'upgrading/upgrading-react-on-rails',
        {
          type: 'link',
          label: 'Full Changelog (GitHub)',
          href: 'https://github.com/shakacode/react_on_rails/blob/main/CHANGELOG.md',
        },
        {
          type: 'category',
          label: 'Release Notes',
          items: [
            'upgrading/release-notes/16.4.0',
            'upgrading/release-notes/16.3.0',
            'upgrading/release-notes/16.2.0',
            'upgrading/release-notes/16.1.0',
            'upgrading/release-notes/16.0.0',
            'upgrading/release-notes/15.0.0',
          ],
        },
        'pro/updating',
        'pro/major-performance-breakthroughs-upgrade-guide',
        {
          type: 'category',
          label: 'Pro Release Notes',
          items: ['pro/release-notes/v4-react-server-components', 'pro/release-notes/4.0'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Migrating',
      items: [
        'migrating/migrating-from-react-rails',
        'migrating/migrating-from-vite-rails',
        'migrating/migrating-from-webpack-to-rspack',
        'migrating/babel-to-swc-migration',
        'migrating/convert-rails-5-api-only-app',
        'migrating/angular-js-integration-migration',
      ],
    },
    {
      type: 'category',
      label: 'React on Rails Pro',
      link: { type: 'doc', id: 'pro/react-on-rails-pro' },
      items: [
        'pro/home-pro',
        'pro/installation',
        'pro/upgrading-to-pro',
        'pro/streaming-ssr',
        'pro/node-renderer',
        'pro/fragment-caching',
        'pro/js-memory-leaks',
        'pro/profiling-server-side-rendering-code',
        'pro/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Contributor Guide',
      items: ['misc/doctrine', 'misc/style', 'misc/credits', 'misc/updating-dependencies'],
    },
    {
      type: 'category',
      label: 'Resources',
      items: ['misc/articles', 'misc/tips'],
    },
  ],
};

export default sidebars;
